name = "Navier"
version = "0.1.0"
defaultTargets = ["Navier"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.34.0-rc2"

[[lean_lib]]
name = "Navier"

[[lean_exe]]
name = "navier"
root = "Main"
