import Navier.Problem
import Navier.OfficialProblem
import Navier.OfficialSurfaceSignatures
import Navier.Analysis.PeriodicQuotientBridge
import Navier.Analysis.HalfSpaceConsumerBridge
import Navier.Analysis.Covariance
import Navier.Analysis.CriticalL3
import Navier.Analysis.CriticalL3Integrable
import Navier.Analysis.CriticalLp
import Navier.Analysis.CriticalProfileAction
import Navier.Analysis.ESSInputs
import Navier.Analysis.CKNCylinderGeometry
import Navier.Analysis.CKNMeasureTransport
import Navier.Analysis.CKNDensity
import Navier.Analysis.CKNIntegralScaling
import Navier.Analysis.OfficialABEncoding
import Navier.Analysis.EnergyNormBridge
import Navier.Analysis.EnergyOfficialClause
import Navier.Analysis.ForceNormBridge
import Navier.Analysis.ForceCoordinateBridge
import Navier.Analysis.ForceCoordinateDecayBridge
import Navier.Analysis.ForceMultiIndexConvention
import Navier.Analysis.ForceMultiIndexObstruction
import Navier.Analysis.TypedCoordinateEndpoints
import Navier.Analysis.LerayProjection
import Navier.Analysis.FrequencyHeatLeray
import Navier.Analysis.FrequencyDuhamel
import Navier.Analysis.ComplexLerayProjection
import Navier.Analysis.ComplexLerayNorm
import Navier.Analysis.ComplexFrequencyHeatLeray
import Navier.Analysis.VectorCalculus
import Navier.Analysis.CurlIdentities
import Navier.Analysis.EnergyPressureCancellation
import Navier.Analysis.EnergyPressureIntegral
import Navier.Analysis.EnergyConvectionCancellation
import Navier.Analysis.EnergyConvectionIntegral
import Navier.Analysis.EnergyTimeDerivative
import Navier.Analysis.EnergyViscousDissipation
import Navier.Analysis.EnergyViscousIntegral
import Navier.Analysis.EnergyPointwiseBalance
import Navier.Analysis.EnergyInstantaneousIntegralBalance
import Navier.Analysis.EnergyDerivativeUnderIntegral
import Navier.Analysis.Vorticity
import Navier.Analysis.VorticityTransport
import Navier.Analysis.ConvectionCurl
import Navier.Analysis.BiotSavartKernel
import Navier.Analysis.SingularIntegralPrelims
import Navier.Analysis.CZNearField
import Navier.Analysis.WeightIntegrability
import Navier.Analysis.SobolevEmbedding
import Navier.Analysis.Ladyzhenskaya
import Navier.Analysis.ConvectionTrilinear
import Navier.Analysis.SobolevGNS
import Navier.Analysis.ConvectionLadyzhenskaya
import Navier.Analysis.FourierMajorant
import Navier.Analysis.FourierWeightedPlancherel
import Navier.Analysis.FourierBridge
import Navier.Analysis.BealeKatoMajda
import Navier.Analysis.VacuityAudit
import Navier.Analysis.BKMLogBootstrap
import Navier.Analysis.BKMLogBootstrapAnalysis
import Navier.Analysis.GagliardoNirenberg
import Navier.Analysis.Enstrophy
import Navier.Analysis.EnstrophyPointwise
import Navier.Analysis.LocalEnstrophyBalance
import Navier.Analysis.CutoffEnstrophy
import Navier.Analysis.CutoffIntegrationByParts
import Navier.Analysis.ScaledCutoff
import Navier.Analysis.EnstrophyLimit
import Navier.Analysis.FrequencyCascadeObstruction
import Navier.Analysis.MultiFrequencyMild
import Navier.Analysis.FrequencyMildGlobal
import Navier.Analysis.DissipativeODEGlobal
import Navier.Analysis.EnergyDissipation
import Navier.Analysis.GalerkinBasis
import Navier.Analysis.GalerkinModeData
import Navier.Analysis.GalerkinHMinusOne
import Navier.Analysis.DivFreeGradientEnstrophy
import Navier.Analysis.LerayWeak
import Navier.Analysis.LerayWeakExistence
import Navier.Analysis.ConditionalRegularity
import Navier.Analysis.SeeleyExtension
import Navier.Analysis.SeeleyMoments
import Navier.Analysis.SeeleyReflection
import Navier.Analysis.SeeleyGlue
import Navier.Analysis.SeeleySynthesis
import Navier.Analysis.ViscosityTransport
import Navier.Analysis.ViscosityAdmissibility
import Navier.Analysis.ViscosityForceDecay
import Navier.Analysis.ViscosityEndpoints
import Navier.Scaling
import Navier.EnergyObstruction
import Navier.ConventionBridges
import Navier.Analysis.SchwartzComponentBound
import Navier.Analysis.UniformDecayDominated
import Navier.Analysis.HeatSemigroupSmoothing
import Navier.Analysis.RieszKolmogorov
import Navier.Analysis.SchwartzConventionEquivalence
import Navier.Analysis.CoordinatePDEBridge
import Navier.Analysis.HalfSpaceSmoothnessBridge
import Navier.Analysis.GramSchmidt
import Navier.Breakdown.MaximalNonextension
import Navier.Analysis.ParabolicCaccioppoli
import Navier.Analysis.PressurePoisson
import Navier.Analysis.PressureNormalization
import Navier.Breakdown.Restriction
import Navier.Breakdown.ForceRecovery
import Navier.Breakdown.OfficialCDEncoding
import Navier.Routes.R7.ExactSymbol
import Navier.Routes.R7.Triad
import Navier.Routes.R7.ScaledTriad
import Navier.Routes.R7.PhaseSymbol
import Navier.Routes.R7.SymmetrizedPhase
import Navier.Routes.R7.SymmetrizedWitness
import Navier.Routes.R7.WeightedShellTransfer
import Navier.Routes.R7.FieldLeakage
import Navier.Routes.R7.FullFieldLeakage
import Navier.Routes.R7.FullSixModePairClassification
import Navier.Routes.R7.FullSixModeReceiverRates
import Navier.Routes.R7.FullSixModeBalance
import Navier.Routes.R7.GeneratedSupport
import Navier.Routes.R7.FiniteConvolution
import Navier.Routes.R7.FiniteAmplitudeDynamics
import Navier.Routes.R7.FiniteReality
import Navier.Routes.R7.FiniteSupportClosureObstruction
import Navier.Routes.R7.GeneratedSupportStrictGrowth
import Navier.Disposition
import Navier.Frontier
import Navier.ProblemFrontier
import Navier.AxiomAudit
import Navier.Analysis.CriticalMildSelfMap
import Navier.Analysis.CriticalMildDuhamelBochner
import Navier.Analysis.CriticalMildHeatCarrierAlgebra
import Navier.Analysis.CriticalMildHeatFlowLinear
import Navier.Analysis.CriticalMildPathFixedPoint
import Navier.Analysis.CriticalMildRestart
import Navier.Analysis.CriticalMildRestartFixedPoint
import Navier.Analysis.CriticalMildLocalSelection
import Navier.Analysis.CriticalMildReachableTimes
import Navier.Analysis.GlobalRegularityCrownCore
import Navier.Analysis.LeiLinCriticalMechanism
import Navier.Analysis.WienerAlgebraConvolution
import Navier.Analysis.LeiLinSpace
import Navier.Analysis.LeiLinLinearEstimate
import Navier.Analysis.ContinuousLeiLinSpace
import Navier.Analysis.ContinuousLeiLinTimeDuhamel
import Navier.Analysis.GlobalRegularityEndpoint
import Navier.Analysis.CriticalControlDecomposition
import Navier.Analysis.ZeroDataGlobal
import Navier.Analysis.LeiLinBilinear
import Navier.Analysis.LeiLinFixedPoint
import Navier.Analysis.LeiLinSmallDataObstruction
import Navier.Analysis.LeiLinCoerciveTerminal
import Navier.Analysis.LeiLinTimeMixed
import Navier.Analysis.LeiLinPositiveRestart

/-!
# Navier

Umbrella module for the official A--D surfaces, parabolic and viscosity
covariance, viscosity-one endpoint reductions, critical `L3` scaling,
point-breakdown consumers, vector-calculus and guarded energy-identity leaves,
algebraic scaling facts, frequencywise heat--Leray infrastructure, the R7
symmetrized and recursively generated finite Fourier tests, proof-bearing
dispositions, finite frontier map, and raw public axiom audit.
The problem endpoint remains conjectural; importing this module does not claim a
solution of the global regularity problem.
-/
