import Navier.Routes.R7.FullFieldLeakage

/-!
# Finite recursive support generated by exact Fourier addition

This file packages the finite wavevector closure forced by quadratic Fourier
convolution.  Generation zero is the six signed R7 witness modes, and each
successor generation retains its predecessor while adjoining every pairwise
sum.  The selected leakage wave is therefore absent initially at nonzero
scale but appears after one generation.

These are support-combinatorics statements only.  They do not prove that the
generated modes carry compatible amplitudes, solve the Navier--Stokes
equations, stabilize after finitely many generations, or satisfy a
scale-uniform shell estimate.
-/

set_option autoImplicit false

noncomputable section

namespace Navier.Routes.R7

/-- The six signed wavevectors of the exact R7 witness at scale `s`. -/
def sixModeInitialSupport (s : ℝ) : Finset Space := by
  classical
  exact Finset.univ.image (scaledSymWitnessModeWave s)

/-- The finite pairwise Minkowski sum `S + S`. -/
def pairwiseMinkowskiSum (S : Finset Space) : Finset Space := by
  classical
  exact (S ×ˢ S).image (fun pair => pair.1 + pair.2)

/-- Preserve the current support and adjoin one quadratic convolution layer. -/
def generatedSupportStep (S : Finset Space) : Finset Space := by
  classical
  exact S ∪ pairwiseMinkowskiSum S

/-- Recursive finite supports generated by exact pairwise wavevector addition. -/
def generatedSupport (s : ℝ) : ℕ → Finset Space
  | 0 => sixModeInitialSupport s
  | n + 1 => generatedSupportStep (generatedSupport s n)

/-- A generation step never discards an already occupied wavevector. -/
theorem subset_generatedSupportStep (S : Finset Space) :
    S ⊆ generatedSupportStep S := by
  classical
  intro k hk
  exact Finset.mem_union_left _ hk

/-- Every pair of occupied wavevectors contributes its sum to the next step. -/
theorem add_mem_generatedSupportStep
    {S : Finset Space} {k l : Space} (hk : k ∈ S) (hl : l ∈ S) :
    k + l ∈ generatedSupportStep S := by
  classical
  apply Finset.mem_union_right S
  rw [pairwiseMinkowskiSum, Finset.mem_image]
  exact ⟨(k, l), by simpa using And.intro hk hl, rfl⟩

/-- Each recursive support is contained in its successor. -/
theorem generatedSupport_subset_succ (s : ℝ) (n : ℕ) :
    generatedSupport s n ⊆ generatedSupport s (n + 1) := by
  change generatedSupport s n ⊆ generatedSupportStep (generatedSupport s n)
  exact subset_generatedSupportStep _

/-- The recursive support sequence is monotone under inclusion. -/
theorem generatedSupport_mono (s : ℝ) :
    Monotone (generatedSupport s) := by
  intro m n hmn
  induction hmn with
  | refl =>
      exact fun _ hk => hk
  | @step n hmn ih =>
      exact Finset.Subset.trans ih (generatedSupport_subset_succ s n)

/-- A pair occupied at generation `n` has its sum occupied at generation `n+1`. -/
theorem add_mem_generatedSupport_succ
    {s : ℝ} {n : ℕ} {k l : Space}
    (hk : k ∈ generatedSupport s n) (hl : l ∈ generatedSupport s n) :
    k + l ∈ generatedSupport s (n + 1) := by
  change k + l ∈ generatedSupportStep (generatedSupport s n)
  exact add_mem_generatedSupportStep hk hl

/-- Every declared signed R7 wavevector occurs at generation zero. -/
theorem scaledSymWitnessModeWave_mem_generatedSupport_zero
    (s : ℝ) (mode : SymWitnessMode) :
    scaledSymWitnessModeWave s mode ∈ generatedSupport s 0 := by
  classical
  rw [generatedSupport, sixModeInitialSupport, Finset.mem_image]
  exact ⟨mode, Finset.mem_univ _, rfl⟩

/-- Every declared signed R7 wavevector persists through every generation. -/
theorem scaledSymWitnessModeWave_mem_generatedSupport
    (s : ℝ) (mode : SymWitnessMode) (n : ℕ) :
    scaledSymWitnessModeWave s mode ∈ generatedSupport s n :=
  generatedSupport_mono s (Nat.zero_le n)
    (scaledSymWitnessModeWave_mem_generatedSupport_zero s mode)

/-- At nonzero scale, the selected leakage wave is absent at generation zero. -/
theorem leakOutputWave_not_mem_generatedSupport_zero
    {s : ℝ} (hs : s ≠ 0) :
    leakOutputWave s ∉ generatedSupport s 0 := by
  intro hmem
  apply leakOutputWave_not_in_six_mode_support hs
  rw [generatedSupport, sixModeInitialSupport, Finset.mem_image] at hmem
  rcases hmem with ⟨mode, _, hmode⟩
  exact ⟨mode, hmode.symm⟩

/-- The selected leakage wave is the explicit sum of modes `negK` and `posL`. -/
theorem leakOutputWave_eq_negK_add_posL (s : ℝ) :
    leakOutputWave s =
      scaledSymWitnessModeWave s .negK +
        scaledSymWitnessModeWave s .posL := by
  simp [leakOutputWave, scaledSymWitnessModeWave]

/-- The explicit `negK + posL` interaction enters after one generation. -/
theorem leakOutputWave_mem_generatedSupport_one (s : ℝ) :
    leakOutputWave s ∈ generatedSupport s 1 := by
  rw [leakOutputWave_eq_negK_add_posL]
  apply add_mem_generatedSupportStep
  · exact scaledSymWitnessModeWave_mem_generatedSupport_zero s .negK
  · exact scaledSymWitnessModeWave_mem_generatedSupport_zero s .posL

/-- At nonzero scale the selected leakage wave first enters between
generations zero and one. -/
theorem leakOutputWave_enters_at_generation_one
    {s : ℝ} (hs : s ≠ 0) :
    leakOutputWave s ∉ generatedSupport s 0 ∧
      leakOutputWave s ∈ generatedSupport s 1 :=
  ⟨leakOutputWave_not_mem_generatedSupport_zero hs,
    leakOutputWave_mem_generatedSupport_one s⟩

/-- A finite support is centrally symmetric when it contains the negative of
each of its occupied wavevectors. -/
def CentrallySymmetricSupport (S : Finset Space) : Prop :=
  ∀ k ∈ S, -k ∈ S

/-- The six signed witness modes form a centrally symmetric support. -/
theorem sixModeInitialSupport_centrallySymmetric (s : ℝ) :
    CentrallySymmetricSupport (sixModeInitialSupport s) := by
  classical
  intro k hk
  rw [sixModeInitialSupport, Finset.mem_image] at hk ⊢
  rcases hk with ⟨mode, _, rfl⟩
  refine ⟨mode.opposite, Finset.mem_univ _, ?_⟩
  cases mode <;>
    simp [SymWitnessMode.opposite, scaledSymWitnessModeWave]

/-- Pairwise Minkowski addition preserves central symmetry. -/
theorem pairwiseMinkowskiSum_centrallySymmetric
    {S : Finset Space} (hS : CentrallySymmetricSupport S) :
    CentrallySymmetricSupport (pairwiseMinkowskiSum S) := by
  classical
  intro x hx
  rw [pairwiseMinkowskiSum, Finset.mem_image] at hx ⊢
  rcases hx with ⟨⟨k, l⟩, hkl, rfl⟩
  rw [Finset.mem_product] at hkl
  refine ⟨(-k, -l), ?_, ?_⟩
  · rw [Finset.mem_product]
    exact ⟨hS k hkl.1, hS l hkl.2⟩
  · simp [add_comm]

/-- Retention plus pairwise Minkowski addition preserves central symmetry. -/
theorem generatedSupportStep_centrallySymmetric
    {S : Finset Space} (hS : CentrallySymmetricSupport S) :
    CentrallySymmetricSupport (generatedSupportStep S) := by
  classical
  intro x hx
  rw [generatedSupportStep, Finset.mem_union] at hx ⊢
  rcases hx with hx | hx
  · exact Or.inl (hS x hx)
  · exact Or.inr (pairwiseMinkowskiSum_centrallySymmetric hS x hx)

/-- Every recursively generated support remains centrally symmetric. -/
theorem generatedSupport_centrallySymmetric (s : ℝ) (n : ℕ) :
    CentrallySymmetricSupport (generatedSupport s n) := by
  induction n with
  | zero =>
      exact sixModeInitialSupport_centrallySymmetric s
  | succ n ih =>
      exact generatedSupportStep_centrallySymmetric ih

end Navier.Routes.R7
