import Navier.Analysis.ContinuousLeiLinBoxD3Maximal

/-!
# Actual-box D3 from almost-everywhere Duhamel sections

This module closes the maximal-regularity mismatch in the actual Lei--Lin
`D₃` estimate.  Product integrability supplies spatial `X¹` integrability for
almost every output time, which is exactly what the time-integrated estimate
uses.  No claim is made about exceptional time sections.
-/

set_option autoImplicit false
set_option maxHeartbeats 3000000
noncomputable section

open MeasureTheory Set Filter Topology BigOperators
open scoped NNReal ENNReal
open Navier.Analysis.ContinuousLeiLinSpace
open Navier.Analysis.ContinuousLeiLinTimeDuhamel
open Navier.Analysis.ComplexLerayNorm
open Navier.Analysis.ContinuousLeiLinDissipation
open Navier.Analysis.ContinuousLeiLinSelfMap
open Navier.Analysis.ContinuousLeiLinRecentTailJoint
open Navier.Analysis.ContinuousLeiLinMixedX1
open Navier.Analysis.ContinuousLeiLinBoxD3Measurability
open Navier.Analysis.ContinuousLeiLinBoxD3Output
open Navier.Analysis.ContinuousLeiLinBoxD3Maximal
open Navier.Analysis.ContinuousLeiLinActualSlots
open Navier.Analysis.ContinuousLeiLinEverywhereRepresentative
open Navier.Analysis.ContinuousLeiLinBoxProduct
open Navier.Analysis.ContinuousLeiLinBoxInterpolation
open Navier.Analysis.ContinuousLeiLinBoxB1Joint

namespace Navier.Analysis.ContinuousLeiLinBoxD3AE

/-- The actual-box `D₃` estimate from datum measurability and one joint
nonlinear-source measurability fact.  The Duhamel `L¹_t X¹` bound and its
spatial sections are generated by maximal regularity; only almost-everywhere
section integrability is used. -/
theorem integral_coordinateX1Mass_continuousMildImage_le_of_actualBox_joint_ae
    (ν : ℝ≥0) (hν : 0 < ν) (T xm1Radius x1WeightedRadius : ℝ)
    (hT : 0 ≤ T)
    (a : ES → ComplexSpace)
    (haM : ∀ i : Fin 3, AEStronglyMeasurable (fun ξ : ES => a ξ i) volume)
    (ha : ∀ i : Fin 3, Integrable (fun ξ : ES => ‖ξ‖⁻¹ * ‖a ξ i‖))
    (ha1 : ∀ i : Fin 3, Integrable (fun ξ : ES => ‖ξ‖ * ‖a ξ i‖))
    (x : ActualLinkedBox ν T xm1Radius x1WeightedRadius)
    (hjoint : AEStronglyMeasurable (fun p : ES × ℝ =>
      complexEuclideanPoint (continuousNavierSource
        (everywhereRawRepresentative ν T x.1)
        (everywhereRawRepresentative ν T x.1) p.2 p.1))
      (volume.prod (volume.restrict (Icc (0 : ℝ) T)))) :
    ∫ t in Icc (0 : ℝ) T, coordinateX1Mass
      (continuousMildImage (ν : ℝ) (by exact_mod_cast hν) a
        (everywhereRawRepresentative ν T x.1) t) ≤
      (ν : ℝ)⁻¹ * coordinateXm1Mass a +
        (3 : ℝ) * (ν : ℝ)⁻¹ * ∫ s in Icc (0 : ℝ) T,
          coordinateXm1Mass (everywhereRawRepresentative ν T x.1 s) *
            coordinateX1Mass (everywhereRawRepresentative ν T x.1 s) := by
  let u := everywhereRawRepresentative ν T x.1
  let μ := volume.restrict (Icc (0 : ℝ) T)
  have hνR : 0 < (ν : ℝ) := by exact_mod_cast hν
  have hcoord (i : Fin 3) : AEStronglyMeasurable (fun p : ES × ℝ =>
      continuousNavierSource u u p.2 p.1 i) (volume.prod μ) :=
    continuousNavierSource_coord_aestronglyMeasurable u u 0 T
      (by simpa [u, μ] using hjoint) i
  have hDjoint (i : Fin 3) : AEStronglyMeasurable (fun p : ES × ℝ =>
      continuousDuhamel (ν : ℝ) u u p.2 p.1 i) (volume.prod μ) :=
    continuousDuhamel_coord_joint_aestronglyMeasurable (ν : ℝ) T u u i (hcoord i)
  have hsource := integrable_weightedContinuousNavierSource_of_actualBox
    ν hν T xm1Radius x1WeightedRadius x T ⟨hT, le_rfl⟩ hjoint
  have hsourceCoord (i : Fin 3) :=
    integrable_weightedContinuousNavierSource_coord_of_actualBox
      ν hν T xm1Radius x1WeightedRadius x T ⟨hT, le_rfl⟩ hjoint i
  have hi : Integrable (fun s : ℝ => ∫ ξ : ES, ‖ξ‖⁻¹ *
      complexEuclideanNorm (continuousNavierSource u u s ξ)) μ := by
    apply hsource.integral_norm_prod_right.congr
    filter_upwards with s
    apply integral_congr_ae
    filter_upwards with ξ
    exact Real.norm_of_nonneg (mul_nonneg (inv_nonneg.mpr (norm_nonneg ξ)) (by
      unfold complexEuclideanNorm
      exact norm_nonneg _))
  have hg (i : Fin 3) : Integrable (fun s : ℝ =>
      normXm1 (fun ξ : ES => continuousNavierSource u u s ξ i)) μ := by
    apply (hsourceCoord i).integral_norm_prod_right.congr
    filter_upwards with s
    unfold normXm1
    apply integral_congr_ae
    filter_upwards with ξ
    exact Real.norm_of_nonneg (mul_nonneg
      (inv_nonneg.mpr (norm_nonneg ξ)) (norm_nonneg _))
  have hJ (i : Fin 3) : AEMeasurable (fun p : ES × ℝ =>
      ENNReal.ofReal (‖p.1‖⁻¹ * ‖continuousNavierSource u u p.2 p.1 i‖))
      (volume.prod μ) :=
    ENNReal.measurable_ofReal.comp_aemeasurable
      (((show AEStronglyMeasurable (fun p : ES × ℝ => ‖p.1‖⁻¹ : ES × ℝ → ℝ)
        (volume.prod μ) by fun_prop).mul (hcoord i).norm).aemeasurable)
  obtain ⟨hs1, hb0⟩ := continuousNavierSource_fixedTime_inputs_of_actualBox
    ν hν T xm1Radius x1WeightedRadius x
  obtain ⟨hu, hu0⟩ := everywhereRawRepresentative_fixedTime_inputs
    ν hν T xm1Radius x1WeightedRadius x
  have hW1 (i : Fin 3) (r : ℝ) (hr : r ∈ Icc (0 : ℝ) T) : AEMeasurable
      (fun p : ES × ℝ => mixedKernelFun u u i (ν : ℝ) p.1 r p.2)
      (volume.prod μ) := by
    change AEMeasurable (fun p : ES × ℝ =>
      ENNReal.ofReal ‖continuousNavierSource u u p.2 p.1 i‖ *
        (if p.2 ≤ r then ENNReal.ofReal
          (‖p.1‖ * Real.exp (-((ν : ℝ) * ‖p.1‖ ^ 2 * (r - p.2)))) else 0))
      (volume.prod μ)
    exact (ENNReal.measurable_ofReal.comp_aemeasurable
      (hcoord i).norm.aemeasurable).mul
        ((Measurable.ite (measurableSet_le measurable_snd measurable_const)
          (ENNReal.measurable_ofReal.comp (by fun_prop)) measurable_const).aemeasurable)
  have hW (i : Fin 3) : AEMeasurable
      (fun z : ℝ × (ES × ℝ) => mixedKernelFun u u i (ν : ℝ) z.2.1 z.1 z.2.2)
      (μ.prod (volume.prod μ)) := by
    have hcoord3 : AEStronglyMeasurable (fun z : ℝ × (ES × ℝ) =>
        continuousNavierSource u u z.2.2 z.2.1 i)
        (μ.prod (volume.prod μ)) :=
      (hcoord i).comp_quasiMeasurePreserving Measure.quasiMeasurePreserving_snd
    change AEMeasurable (fun z : ℝ × (ES × ℝ) =>
      ENNReal.ofReal ‖continuousNavierSource u u z.2.2 z.2.1 i‖ *
        (if z.2.2 ≤ z.1 then ENNReal.ofReal
          (‖z.2.1‖ * Real.exp (-((ν : ℝ) * ‖z.2.1‖ ^ 2 *
            (z.1 - z.2.2)))) else 0))
      (μ.prod (volume.prod μ))
    exact (ENNReal.measurable_ofReal.comp_aemeasurable
      hcoord3.norm.aemeasurable).mul
        ((Measurable.ite
          (measurableSet_le (measurable_snd.comp measurable_snd) measurable_fst)
          (ENNReal.measurable_ofReal.comp (by fun_prop)) measurable_const).aemeasurable)
  have hDfacts (i : Fin 3) := continuousDuhamel_X1_integrability
    u u (ν : ℝ) T i hνR (hDjoint i) (hW1 i) (hW i)
      (fun s _ => hb0 s i) (hg i) (hJ i)
  have hD0 (i : Fin 3) : Integrable (fun t : ℝ =>
      normX1 (fun ξ : ES => continuousDuhamel (ν : ℝ) u u t ξ i)) μ :=
    (hDfacts i).1
  have hDξ (i : Fin 3) : ∀ᵐ t ∂μ,
      Integrable (fun ξ : ES =>
        ‖ξ‖ * ‖continuousDuhamel (ν : ℝ) u u t ξ i‖) :=
    (hDfacts i).2
  have hImeas : AEStronglyMeasurable (fun t : ℝ => coordinateX1Mass
      (continuousMildImage (ν : ℝ) hνR a u t)) μ :=
    coordinateX1Mass_continuousMildImage_aestronglyMeasurable
      (ν : ℝ) T hνR a haM u (by simpa [u, μ] using hjoint)
  have hHt : Integrable (fun t : ℝ => coordinateX1Mass
      (heatVec (ν : ℝ) t a)) μ :=
    integrable_coordinateX1Mass_heatVec_on_Icc a ha1 (ν : ℝ) T hνR
  have hDt : Integrable (fun t : ℝ => coordinateX1Mass
      (continuousDuhamel (ν : ℝ) u u t)) μ := by
    unfold coordinateX1Mass
    exact integrable_finsetSum (f := fun i (t : ℝ) =>
      normX1 (fun ξ : ES => continuousDuhamel (ν : ℝ) u u t ξ i))
      Finset.univ (fun i _ => hD0 i)
  have hDξall : ∀ᵐ t ∂μ, ∀ i : Fin 3,
      Integrable (fun ξ : ES =>
        ‖ξ‖ * ‖continuousDuhamel (ν : ℝ) u u t ξ i‖) :=
    Filter.eventually_all.mpr hDξ
  have hIt : Integrable (fun t : ℝ => coordinateX1Mass
      (continuousMildImage (ν : ℝ) hνR a u t)) μ := by
    apply (hHt.add hDt).mono' hImeas
    filter_upwards [ae_restrict_mem isClosed_Icc.measurableSet, hDξall] with t ht hDξt
    have hle := coordinateX1Mass_add_le (heatVec (ν : ℝ) t a)
      (continuousDuhamel (ν : ℝ) u u t)
      (fun i => integrable_weighted_heatMode_of_X1
        (fun ξ : ES => a ξ i) (ha1 i) (ν : ℝ) t hνR ht.1)
      hDξt
    rw [Real.norm_of_nonneg (coordinateX1Mass_nonneg _)]
    change coordinateX1Mass (fun ξ => heatVec (ν : ℝ) t a ξ +
      continuousDuhamel (ν : ℝ) u u t ξ) ≤ _
    exact hle
  refine integral_coordinateX1Mass_continuousMildImage_le_ae
    (ν : ℝ) hνR a ha ha1 u T hT hIt hHt hD0 hDξ ?_ ?_
      (fun i s _ => hb0 s i) hg hJ (fun s _ => hs1 s) hi hu hu0
      (everywhereRawRepresentative_xm1_integrable ν T x.1)
      (everywhereRawRepresentative_x1_integrable ν T x.1)
      (integrableOn_coordinateX0Mass_sq_everywhere_of_mem_box
        ν hν T xm1Radius x1WeightedRadius x T ⟨hT, le_rfl⟩)
      (integrable_coordinateXm1_mul_X1_everywhere_of_mem_box
        ν hν T xm1Radius x1WeightedRadius x)
  · exact hW1
  · exact hW

end Navier.Analysis.ContinuousLeiLinBoxD3AE

set_option pp.fullNames true in
#print axioms Navier.Analysis.ContinuousLeiLinBoxD3AE.integral_coordinateX1Mass_continuousMildImage_le_of_actualBox_joint_ae
set_option pp.fullNames true in
#print axioms Navier.Analysis.ContinuousLeiLinSelfMap.integral_coordinateX1Mass_continuousMildImage_le_ae
