import Navier.Analysis.CriticalMildSmoothBootstrap

/-!
# Local uniform positive-time bootstrap bounds

This module transports one admissible terminal cutoff across a compact
positive-time interval.  The resulting common cutoff gap turns the pointwise
positive-time graph estimate into a single uniform half-generator bound.
That uniformity is the domination input required for termwise time
differentiation of the evolving Fourier series.

The bounds remain local to one mild chart and one compact positive-time
interval.  No horizon-uniform or arbitrary-data global estimate is asserted.
-/

set_option autoImplicit false
set_option maxHeartbeats 1000000

noncomputable section

open scoped BigOperators ENNReal
open MeasureTheory Set

namespace Navier.Analysis.CriticalMildLocalUniformBootstrap

open Navier
open Navier.Analysis.ComplexLerayNorm
open Navier.Analysis.OfficialABEncoding
open Navier.Analysis.CriticalMildSeries
open Navier.Analysis.CriticalMildWeightedSpace
open Navier.Analysis.CriticalMildWeightedBanach
open Navier.Analysis.CriticalMildDuhamelBochner
open Navier.Analysis.CriticalMildSelfMap
open Navier.Analysis.CriticalMildHeatSmoothing
open Navier.Analysis.CriticalMildHeatFlowLinear
open Navier.Analysis.CriticalMildInteriorTimeModulus
open Navier.Analysis.CriticalMildFullPositiveTimeRegularity
open Navier.Analysis.CriticalMildAsymmetricPairSummable
open Navier.Analysis.CriticalMildGlobalWeightedOutput
open Navier.Analysis.CriticalMildSmoothBootstrap
open Navier.Analysis.CriticalMildModeDifferentiation

/-- An admissible cutoff at the left endpoint transports with the same gap
to every later time in a compact interval. -/
theorem transported_admissible_terminalWindow
    {b₀ a t : ℝ} (hb₀ : 0 < b₀) (hb₀a : b₀ < a)
    (hunit : a - b₀ ≤ 1) (hinterior : Real.sqrt (a - b₀) < b₀)
    (hat : a ≤ t) :
    0 < t - (a - b₀) ∧
      t - (a - b₀) < t ∧
      t - (t - (a - b₀)) ≤ 1 ∧
      Real.sqrt (t - (t - (a - b₀))) < t - (a - b₀) := by
  have hgap : 0 < a - b₀ := sub_pos.mpr hb₀a
  have hbtransport : b₀ ≤ t - (a - b₀) := by linarith
  constructor
  · exact hb₀.trans_le hbtransport
  constructor
  · linarith
  constructor
  · rw [show t - (t - (a - b₀)) = a - b₀ by ring]
    exact hunit
  · rw [show t - (t - (a - b₀)) = a - b₀ by ring]
    exact hinterior.trans_le hbtransport

/-- The explicit quarter-Hölder window constant is monotone when its lower
endpoint moves right and its upper endpoint moves left. -/
theorem interiorQuarterWindowConstant_mono
    (ν : ℝ) (hν : 0 < ν) (u₀ : WeightedLatticeBanach) (R : ℝ)
    {b₀ b t T : ℝ} (hb₀ : 0 < b₀) (hb₀b : b₀ ≤ b) (htT : t ≤ T) :
    interiorQuarterWindowConstant ν u₀ R b t ≤
      interiorQuarterWindowConstant ν u₀ R b₀ T := by
  have hνb₀ : 0 < ν * b₀ := mul_pos hν hb₀
  have hνb : 0 < ν * b := mul_pos hν (hb₀.trans_le hb₀b)
  have hprod : ν * b₀ ≤ ν * b :=
    mul_le_mul_of_nonneg_left hb₀b hν.le
  have hsqrtprod : Real.sqrt (ν * b₀) ≤ Real.sqrt (ν * b) :=
    Real.sqrt_le_sqrt hprod
  have hinv : (Real.sqrt (ν * b))⁻¹ ≤
      (Real.sqrt (ν * b₀))⁻¹ := by
    simpa only [one_div] using one_div_le_one_div_of_le
      (Real.sqrt_pos.2 hνb₀) hsqrtprod
  have hsqrtt : Real.sqrt t ≤ Real.sqrt T := Real.sqrt_le_sqrt htT
  dsimp [interiorQuarterWindowConstant]
  gcongr

/-- Common Dini budget associated with the transported cutoff gap. -/
def compactDiniBudget
    (ν : ℝ) (u₀ : WeightedLatticeBanach)
    (R a b₀ T : ℝ) : ℝ :=
  T * ((2 / (ν * (a - b₀))) * (2 * R) * (2 * R)) +
    4 * ((4 / ν) * R *
      interiorQuarterWindowConstant ν u₀ R b₀ T) *
        (a - b₀) ^ (1 / 4 : ℝ)

/-- A single explicit scalar dominating every graph moment on the compact
positive-time interval generated by one transported cutoff. -/
def compactHalfGeneratorBudget
    (ν : ℝ) (u₀ : WeightedLatticeBanach)
    (R a b₀ T : ℝ) : ℝ :=
  (Real.sqrt (ν * a))⁻¹ * ‖u₀‖ +
    compactDiniBudget ν u₀ R a b₀ T +
    ν⁻¹ * R ^ 2

/-- Half-generator membership is exactly the extra summability needed to
upgrade the decoded carrier from one to two inhomogeneous lattice weights. -/
theorem latticeTwoWeightL1_of_halfGenerator
    (v : WeightedLatticeBanach)
    (hv : Summable fun k : LatticeMode =>
      ‖complexFrequency (latticeFrequency k)‖ * ‖v k‖) :
    LatticeTwoWeightL1 (weightedLatticeCoefficient v) := by
  have hbase : Summable fun k : LatticeMode => ‖v k‖ := by
    simpa using v.2.summable
  have hsum := hbase.add hv
  apply hsum.congr
  intro k
  rw [← latticeWeightedAmplitude_coefficient v k]
  unfold latticeWeightedAmplitude latticeModeWeight
  ring

/-- The two-weight decoded mass is exactly the carrier norm plus its
half-generator moment. -/
theorem tsum_twoWeight_eq_norm_add_halfGeneratorMoment
    (v : WeightedLatticeBanach)
    (hv : Summable fun k : LatticeMode =>
      ‖complexFrequency (latticeFrequency k)‖ * ‖v k‖) :
    (∑' k : LatticeMode, latticeModeWeight k ^ 2 *
      complexEuclideanNorm (weightedLatticeCoefficient v k)) =
      ‖v‖ + heatHalfGeneratorMoment v := by
  have hbase : Summable fun k : LatticeMode => ‖v k‖ := by
    simpa using v.2.summable
  calc
    (∑' k : LatticeMode, latticeModeWeight k ^ 2 *
        complexEuclideanNorm (weightedLatticeCoefficient v k)) =
        ∑' k : LatticeMode,
          (‖v k‖ +
            ‖complexFrequency (latticeFrequency k)‖ * ‖v k‖) := by
      apply tsum_congr
      intro k
      rw [← latticeWeightedAmplitude_coefficient v k]
      unfold latticeWeightedAmplitude latticeModeWeight
      ring
    _ = (∑' k : LatticeMode, ‖v k‖) +
        ∑' k : LatticeMode,
          ‖complexFrequency (latticeFrequency k)‖ * ‖v k‖ :=
      hbase.tsum_add hv
    _ = ‖v‖ + heatHalfGeneratorMoment v := by
      rw [← tsum_latticeWeightedAmplitude_coefficient v]
      congr 1
      apply tsum_congr
      intro k
      exact (latticeWeightedAmplitude_coefficient v k).symm

/-- Quantitative one-output-weight estimate for the literal projected
forcing, expressed directly through the carrier norm and decoded two-weight
mass. -/
theorem tsum_weighted_projectedModeForcing_le
    (A : ℝ → WeightedLatticeBanach) (t : ℝ)
    (hA : LatticeTwoWeightL1 (weightedLatticeCoefficient (A t))) :
    (∑' k : LatticeMode, latticeModeWeight k *
      complexEuclideanNorm (projectedModeForcing A k t)) ≤
      ‖A t‖ *
        ∑' k : LatticeMode, latticeModeWeight k ^ 2 *
          complexEuclideanNorm (weightedLatticeCoefficient (A t) k) := by
  let hv := latticeWeightedL1_coefficient (A t)
  have hprojected := summable_weighted_projectedModeForcing A t hA
  have houtput := summable_weighted_spectralOutputCoefficient (A t) (A t) hA
  have hglobal := norm_globalWeightedSpectralOutput_le
    (weightedLatticeCoefficient (A t)) (weightedLatticeCoefficient (A t))
      hv hA
  calc
    (∑' k : LatticeMode, latticeModeWeight k *
        complexEuclideanNorm (projectedModeForcing A k t)) ≤
        ∑' k : LatticeMode, latticeModeWeight k *
          complexEuclideanNorm (spectralOutputCoefficient k (A t) (A t)) :=
      hprojected.tsum_le_tsum
        (fun k => mul_le_mul_of_nonneg_left
          (complexEuclideanNorm_complexLeray_le (latticeFrequency k)
            (spectralOutputCoefficient k (A t) (A t)))
          (zero_le_one.trans (one_le_latticeModeWeight k))) houtput
    _ = ‖globalWeightedSpectralOutput
        (weightedLatticeCoefficient (A t)) (weightedLatticeCoefficient (A t))
          hv hA‖ := by
      rw [norm_globalWeightedSpectralOutput_eq_tsum]
      apply tsum_congr
      intro k
      rw [globalWeightedSpectralOutputFiber_eq_actualConvolution k
        (weightedLatticeCoefficient (A t))
        (weightedLatticeCoefficient (A t)) hv hA,
        norm_smul, Real.norm_of_nonneg
          (zero_le_one.trans (one_le_latticeModeWeight k))]
      rfl
    _ ≤ (∑' k : LatticeMode,
          globalWeightedInputFactor (weightedLatticeCoefficient (A t)) k) *
        ∑' k : LatticeMode,
          globalTwoWeightInputFactor (weightedLatticeCoefficient (A t)) k :=
      hglobal
    _ = ‖A t‖ *
        ∑' k : LatticeMode, latticeModeWeight k ^ 2 *
          complexEuclideanNorm (weightedLatticeCoefficient (A t) k) := by
      rw [← tsum_latticeWeightedAmplitude_coefficient (A t)]
      rfl

/-- A half-generator bound gives a quantitative `ℓ¹` bound for the actual
mode derivative.  Both the quadratic forcing and viscous multiplier are
estimated from the same decoded two-weight mass. -/
theorem tsum_mildRawTimeDerivative_le_of_halfGenerator
    (μ : ℝ) (A : ℝ → WeightedLatticeBanach) (t R M : ℝ)
    (hR : 0 ≤ R) (hM : 0 ≤ M)
    (hAt : ‖A t‖ ≤ R)
    (hhalf : Summable fun k : LatticeMode =>
      ‖complexFrequency (latticeFrequency k)‖ * ‖A t k‖)
    (hmoment : heatHalfGeneratorMoment (A t) ≤ M) :
    (Summable fun k : LatticeMode =>
      complexEuclideanNorm (mildRawTimeDerivative μ A t k)) ∧
    (∑' k : LatticeMode,
      complexEuclideanNorm (mildRawTimeDerivative μ A t k)) ≤
        (R + |μ|) * (R + M) := by
  let B : ℝ := R + M
  have hB : 0 ≤ B := by dsimp [B]; positivity
  have htwo := latticeTwoWeightL1_of_halfGenerator (A t) hhalf
  have htwoMass : (∑' k : LatticeMode, latticeModeWeight k ^ 2 *
      complexEuclideanNorm (weightedLatticeCoefficient (A t) k)) ≤ B := by
    rw [tsum_twoWeight_eq_norm_add_halfGeneratorMoment (A t) hhalf]
    exact add_le_add hAt hmoment
  have hforcing := summable_weighted_projectedModeForcing A t htwo
  have hvisc : Summable fun k : LatticeMode => |μ| *
      (latticeModeWeight k ^ 2 *
        complexEuclideanNorm (weightedLatticeCoefficient (A t) k)) :=
    htwo.mul_left |μ|
  have hmajor := hforcing.add hvisc
  have hpoint : ∀ k : LatticeMode,
      complexEuclideanNorm (mildRawTimeDerivative μ A t k) ≤
        latticeModeWeight k *
            complexEuclideanNorm (projectedModeForcing A k t) +
          |μ| * (latticeModeWeight k ^ 2 *
            complexEuclideanNorm (weightedLatticeCoefficient (A t) k)) := by
    intro k
    have hq : ‖officialEuclideanPoint (latticeFrequency k)‖ ≤
        latticeModeWeight k := by
      rw [← complexFrequency_norm_eq_official]
      unfold latticeModeWeight
      linarith [norm_nonneg (complexFrequency (latticeFrequency k))]
    have hq2 : ‖officialEuclideanPoint (latticeFrequency k)‖ ^ 2 ≤
        latticeModeWeight k ^ 2 := by
      nlinarith [norm_nonneg (officialEuclideanPoint (latticeFrequency k)),
        zero_le_one.trans (one_le_latticeModeWeight k)]
    have hviscPoint : complexEuclideanNorm
        ((rawModeDecayRate μ k : ℂ) •
          weightedLatticeCoefficient (A t) k) ≤
        |μ| * (latticeModeWeight k ^ 2 *
          complexEuclideanNorm (weightedLatticeCoefficient (A t) k)) := by
      have hsq : |‖officialEuclideanPoint (latticeFrequency k)‖ ^ 2| =
          ‖officialEuclideanPoint (latticeFrequency k)‖ ^ 2 :=
        abs_of_nonneg (sq_nonneg _)
      unfold rawModeDecayRate complexEuclideanNorm
      rw [ComplexFrequencyHeatLeray.complexEuclideanPoint_smul, norm_smul,
        Complex.norm_real, Real.norm_eq_abs, abs_mul, hsq]
      simpa only [mul_assoc] using mul_le_mul_of_nonneg_left
        (mul_le_mul_of_nonneg_right hq2
          (norm_nonneg (complexEuclideanPoint
            (weightedLatticeCoefficient (A t) k)))) (abs_nonneg μ)
    unfold mildRawTimeDerivative
    calc
      complexEuclideanNorm
          (projectedModeForcing A k t -
            (rawModeDecayRate μ k : ℂ) •
              weightedLatticeCoefficient (A t) k) ≤
          complexEuclideanNorm (projectedModeForcing A k t) +
            complexEuclideanNorm
              ((rawModeDecayRate μ k : ℂ) •
                weightedLatticeCoefficient (A t) k) := by
        unfold complexEuclideanNorm
        change ‖complexEuclideanPoint (projectedModeForcing A k t) -
            complexEuclideanPoint
              ((rawModeDecayRate μ k : ℂ) •
                weightedLatticeCoefficient (A t) k)‖ ≤ _
        exact norm_sub_le _ _
      _ ≤ latticeModeWeight k *
            complexEuclideanNorm (projectedModeForcing A k t) +
          |μ| * (latticeModeWeight k ^ 2 *
            complexEuclideanNorm (weightedLatticeCoefficient (A t) k)) :=
        add_le_add
          (le_mul_of_one_le_left (norm_nonneg _)
            (one_le_latticeModeWeight k)) hviscPoint
  have hderiv := hmajor.of_nonneg_of_le
    (fun k => norm_nonneg _) hpoint
  constructor
  · exact hderiv
  · calc
      (∑' k : LatticeMode,
        complexEuclideanNorm (mildRawTimeDerivative μ A t k)) ≤
          ∑' k : LatticeMode,
            (latticeModeWeight k *
                complexEuclideanNorm (projectedModeForcing A k t) +
              |μ| * (latticeModeWeight k ^ 2 *
                complexEuclideanNorm
                  (weightedLatticeCoefficient (A t) k))) :=
        hderiv.tsum_le_tsum hpoint hmajor
      _ = (∑' k : LatticeMode, latticeModeWeight k *
              complexEuclideanNorm (projectedModeForcing A k t)) +
            |μ| * (∑' k : LatticeMode, latticeModeWeight k ^ 2 *
              complexEuclideanNorm (weightedLatticeCoefficient (A t) k)) := by
        rw [hforcing.tsum_add hvisc, tsum_mul_left]
      _ ≤ ‖A t‖ *
            (∑' k : LatticeMode, latticeModeWeight k ^ 2 *
              complexEuclideanNorm (weightedLatticeCoefficient (A t) k)) +
          |μ| * (∑' k : LatticeMode, latticeModeWeight k ^ 2 *
              complexEuclideanNorm (weightedLatticeCoefficient (A t) k)) :=
        add_le_add (tsum_weighted_projectedModeForcing_le A t htwo) le_rfl
      _ ≤ R * B + |μ| * B :=
        add_le_add
          (mul_le_mul hAt htwoMass
            (tsum_nonneg fun k => mul_nonneg (sq_nonneg _) (norm_nonneg _)) hR)
          (mul_le_mul_of_nonneg_left htwoMass (abs_nonneg _))
      _ = (R + |μ|) * (R + M) := by dsimp [B]; ring

/-- The pointwise Dini budget at every observation time in `[a,T]` is
dominated by the common transported-cutoff budget. -/
theorem mildDiniExplicitBudget_transported_le_compact
    (ν : ℝ) (hν : 0 < ν) (u₀ : WeightedLatticeBanach)
    (R : ℝ) (hR : 0 ≤ R)
    {b₀ a t T : ℝ} (hb₀ : 0 < b₀) (hb₀a : b₀ < a)
    (hat : a ≤ t) (htT : t ≤ T) :
    mildDiniExplicitBudget ν u₀ R (t - (a - b₀)) t ≤
      compactDiniBudget ν u₀ R a b₀ T := by
  let b : ℝ := t - (a - b₀)
  have hgap : 0 < a - b₀ := sub_pos.mpr hb₀a
  have hb₀b : b₀ ≤ b := by dsimp [b]; linarith
  have hb0 : 0 < b := hb₀.trans_le hb₀b
  have hbT : b ≤ T := by dsimp [b]; linarith
  have hC := interiorQuarterWindowConstant_mono
    ν hν u₀ R hb₀ hb₀b htT
  have hCp : 0 ≤ (2 / (ν * (a - b₀))) * (2 * R) * (2 * R) := by
    positivity
  have hfront : 0 ≤ (4 / ν) * R := by positivity
  have hpow : 0 ≤ (a - b₀) ^ (1 / 4 : ℝ) :=
    Real.rpow_nonneg hgap.le _
  change mildDiniExplicitBudget ν u₀ R b t ≤ _
  unfold mildDiniExplicitBudget compactDiniBudget
  rw [show t - b = a - b₀ by dsimp [b]; ring]
  apply add_le_add
  · exact mul_le_mul_of_nonneg_right hbT hCp
  · exact mul_le_mul_of_nonneg_right
      (mul_le_mul_of_nonneg_left
        (mul_le_mul_of_nonneg_left hC hfront) (by norm_num)) hpow

/-- **Uniform half-generator control on every compact positive-time
subinterval of one actual mild chart.**  One cutoff chosen at `a` is
transported to every `t ∈ [a,T]`; the output is a single explicit bound and
not a family of pointwise existential constants. -/
theorem exists_uniform_halfGenerator_on_compactPositiveInterval
    (ν : ℝ) (hν : 0 < ν)
    (u₀ : WeightedLatticeBanach) (hu₀ : LatticeDivergenceFree u₀)
    (u : ℝ → WeightedLatticeBanach) (huc : Continuous u)
    (hu : ∀ s, LatticeDivergenceFree (u s))
    {R a T : ℝ} (hR : 0 ≤ R) (ha : 0 < a) (haT : a ≤ T)
    (huR : ∀ s ∈ Ioc (0 : ℝ) T, ‖u s‖ ≤ R)
    (hmild : ∀ s (hs : s ∈ Icc (0 : ℝ) T),
      u s = criticalMildImage ν hν u₀ u hu s hs.1) :
    ∃ b₀ : ℝ, 0 < b₀ ∧ b₀ < a ∧ a - b₀ ≤ 1 ∧
      Real.sqrt (a - b₀) < b₀ ∧
      0 ≤ compactHalfGeneratorBudget ν u₀ R a b₀ T ∧
      ∀ t ∈ Icc a T,
        (Summable fun k : LatticeMode =>
          ‖complexFrequency (latticeFrequency k)‖ * ‖u t k‖) ∧
        LatticeTwoWeightL1 (weightedLatticeCoefficient (u t)) ∧
        (∑' k : LatticeMode, latticeModeWeight k ^ 2 *
          complexEuclideanNorm (weightedLatticeCoefficient (u t) k)) ≤
            R + compactHalfGeneratorBudget ν u₀ R a b₀ T ∧
        (Summable fun k : LatticeMode =>
          complexEuclideanNorm (mildRawTimeDerivative ν u t k)) ∧
        (∑' k : LatticeMode,
          complexEuclideanNorm (mildRawTimeDerivative ν u t k)) ≤
            (R + |ν|) *
              (R + compactHalfGeneratorBudget ν u₀ R a b₀ T) ∧
        heatHalfGeneratorMoment (u t) ≤
          compactHalfGeneratorBudget ν u₀ R a b₀ T := by
  obtain ⟨b₀, hb₀, hb₀a, hunit, hinterior⟩ :=
    exists_admissible_terminalWindow ha
  have hT : 0 < T := ha.trans_le haT
  have hbudget : 0 ≤ compactHalfGeneratorBudget ν u₀ R a b₀ T := by
    have hgap : 0 < a - b₀ := sub_pos.mpr hb₀a
    have hC : 0 ≤ interiorQuarterWindowConstant ν u₀ R b₀ T := by
      unfold interiorQuarterWindowConstant
      positivity
    have hCp : 0 ≤
        (2 / (ν * (a - b₀))) * (2 * R) * (2 * R) := by
      positivity
    have hterminal : 0 ≤ 4 * ((4 / ν) * R *
        interiorQuarterWindowConstant ν u₀ R b₀ T) *
          (a - b₀) ^ (1 / 4 : ℝ) := by
      positivity
    unfold compactHalfGeneratorBudget compactDiniBudget
    exact add_nonneg
      (add_nonneg
        (mul_nonneg (inv_nonneg.mpr (Real.sqrt_nonneg _)) (norm_nonneg _))
        (add_nonneg (mul_nonneg hT.le hCp) hterminal))
      (mul_nonneg (inv_nonneg.mpr hν.le) (sq_nonneg _))
  refine ⟨b₀, hb₀, hb₀a, hunit, hinterior, hbudget, ?_⟩
  intro t ht
  have ht0 : 0 < t := ha.trans_le ht.1
  have huRt : ∀ s ∈ Ioc (0 : ℝ) t, ‖u s‖ ≤ R := by
    intro s hs
    exact huR s ⟨hs.1, hs.2.trans ht.2⟩
  have hmildt : ∀ s (hs : s ∈ Icc (0 : ℝ) t),
      u s = criticalMildImage ν hν u₀ u hu s hs.1 := by
    intro s hs
    exact hmild s ⟨hs.1, hs.2.trans ht.2⟩
  have hgraph := mildTrajectory_fullPositiveTime_halfGenerator
    ν hν u₀ hu₀ u huc hu hR ht0 huRt hmildt
  let b : ℝ := t - (a - b₀)
  have hbdata := transported_admissible_terminalWindow
    hb₀ hb₀a hunit hinterior ht.1
  have hDini := integral_mildDiniDensity_le_explicitBudget
    ν hν u₀ hu₀ u huc hu hR hbdata.1 hbdata.2.1
      hbdata.2.2.1 hbdata.2.2.2 huRt hmildt
  have hDiniCompact :
      (∫ s in Ioc 0 t, mildDiniDensity ν t u s) ≤
        compactDiniBudget ν u₀ R a b₀ T := by
    exact hDini.trans
      (mildDiniExplicitBudget_transported_le_compact
        ν hν u₀ R hR hb₀ hb₀a ht.1 ht.2)
  have hνa : 0 < ν * a := mul_pos hν ha
  have hνt : 0 < ν * t := mul_pos hν ht0
  have hprod : ν * a ≤ ν * t :=
    mul_le_mul_of_nonneg_left ht.1 hν.le
  have hsqrt : Real.sqrt (ν * a) ≤ Real.sqrt (ν * t) :=
    Real.sqrt_le_sqrt hprod
  have hinv : (Real.sqrt (ν * t))⁻¹ ≤
      (Real.sqrt (ν * a))⁻¹ := by
    simpa only [one_div] using one_div_le_one_div_of_le
      (Real.sqrt_pos.2 hνa) hsqrt
  have hlinear : (Real.sqrt (ν * t))⁻¹ * ‖u₀‖ ≤
      (Real.sqrt (ν * a))⁻¹ * ‖u₀‖ :=
    mul_le_mul_of_nonneg_right hinv (norm_nonneg _)
  have hut : ‖u t‖ ≤ R := huR t ⟨ht0, ht.2⟩
  have hsquare : ‖u t‖ ^ 2 ≤ R ^ 2 :=
    (sq_le_sq₀ (norm_nonneg _) hR).2 hut
  have hviscous : ν⁻¹ * ‖u t‖ ^ 2 ≤ ν⁻¹ * R ^ 2 :=
    mul_le_mul_of_nonneg_left hsquare (inv_nonneg.mpr hν.le)
  have hmoment : heatHalfGeneratorMoment (u t) ≤
      compactHalfGeneratorBudget ν u₀ R a b₀ T := hgraph.2.trans (by
    unfold compactHalfGeneratorBudget
    exact add_le_add (add_le_add hlinear hDiniCompact) hviscous)
  have htwo := latticeTwoWeightL1_of_halfGenerator (u t) hgraph.1
  have htwoMass : (∑' k : LatticeMode, latticeModeWeight k ^ 2 *
      complexEuclideanNorm (weightedLatticeCoefficient (u t) k)) ≤
      R + compactHalfGeneratorBudget ν u₀ R a b₀ T := by
    rw [tsum_twoWeight_eq_norm_add_halfGeneratorMoment (u t) hgraph.1]
    exact add_le_add hut hmoment
  have hderiv := tsum_mildRawTimeDerivative_le_of_halfGenerator
    ν u t R (compactHalfGeneratorBudget ν u₀ R a b₀ T)
      hR hbudget hut hgraph.1 hmoment
  exact ⟨hgraph.1, htwo, htwoMass, hderiv.1, hderiv.2, hmoment⟩

end Navier.Analysis.CriticalMildLocalUniformBootstrap

#print axioms Navier.Analysis.CriticalMildLocalUniformBootstrap.transported_admissible_terminalWindow
#print axioms Navier.Analysis.CriticalMildLocalUniformBootstrap.interiorQuarterWindowConstant_mono
#print axioms Navier.Analysis.CriticalMildLocalUniformBootstrap.latticeTwoWeightL1_of_halfGenerator
#print axioms Navier.Analysis.CriticalMildLocalUniformBootstrap.tsum_twoWeight_eq_norm_add_halfGeneratorMoment
#print axioms Navier.Analysis.CriticalMildLocalUniformBootstrap.tsum_weighted_projectedModeForcing_le
#print axioms Navier.Analysis.CriticalMildLocalUniformBootstrap.tsum_mildRawTimeDerivative_le_of_halfGenerator
#print axioms Navier.Analysis.CriticalMildLocalUniformBootstrap.exists_uniform_halfGenerator_on_compactPositiveInterval
