import Navier.Analysis.PeriodicGlobalCriticalControl

/-!
# Physical reality removes the raw periodic mean instability

The completed critical mild carrier stores the normalization `A = -i û`.
Consequently a real velocity field is represented by an anti-Hermitian lattice
sequence: `A (-m) = -conj (A m)`.  This file proves, for an arbitrary physical
carrier and every lattice mode, that transport by the zero mode is
skew-Hermitian.  Its exact exponential flow preserves modal amplitude; after
viscosity is included, the amplitude decays at precisely the heat rate.

This rules out the real-mean exponential mechanism available in the larger raw
complex carrier.  It does not estimate transfer among nonzero triads.  That
remaining transfer is the genuinely nonlinear input still needed for the
horizon-uniform off-zero terminal bound.
-/

set_option autoImplicit false

noncomputable section

namespace Navier.Analysis.PhysicalPeriodicGlobalControl

open Navier
open Navier.Analysis.ComplexLerayProjection
open Navier.Analysis.ComplexLerayNorm
open Navier.Analysis.ComplexFrequencyHeatLeray
open Navier.Analysis.CriticalMildDuhamel
open Navier.Analysis.CriticalMildSeries
open Navier.Analysis.CriticalMildWeightedBanach

/-- Reality in the repository's weighted `A = -i û` lattice normalization,
using the same predicate that excludes the checked raw-complex counterexample. -/
abbrev PhysicalAntiHermitian :=
  PeriodicGlobalCriticalControl.RawLatticeAntiHermitian

/-- The zero coefficient of a physical carrier is coordinatewise purely
imaginary. -/
theorem zeroMode_realPart_eq_zero
    (u : WeightedLatticeBanach) (hu : PhysicalAntiHermitian u) :
    ComplexLerayProjection.realPart
      (weightedLatticeCoefficient u (0 : LatticeMode)) = 0 := by
  have hzero := hu (0 : LatticeMode)
  simp only [neg_zero] at hzero
  ext i
  have hi := congrArg (fun z : ComplexSpace => (z i).re) hzero
  simp [complexConjugate] at hi
  change (weightedLatticeCoefficient u (0 : LatticeMode) i).re = 0
  linarith

/-- Pairing any real lattice frequency against the physical zero coefficient
has zero real part.  This is the scalar skew-adjointness of mean advection. -/
theorem meanTransportScalar_re_eq_zero
    (u : WeightedLatticeBanach) (hu : PhysicalAntiHermitian u)
    (m : LatticeMode) :
    (inner ℂ (complexFrequency (latticeFrequency m))
      (complexEuclideanPoint
        (weightedLatticeCoefficient u (0 : LatticeMode)))).re = 0 := by
  rw [inner_complexFrequency]
  have hz := zeroMode_realPart_eq_zero u hu
  change Complex.reCLM (∑ i, (latticeFrequency m i : ℂ) *
    weightedLatticeCoefficient u (0 : LatticeMode) i) = 0
  rw [map_sum]
  apply Finset.sum_eq_zero
  intro i hi
  have hzi := congrFun hz i
  simpa [ComplexLerayProjection.realPart, Complex.mul_re] using
    mul_eq_zero_of_right (latticeFrequency m i) hzi

/-- The physical mean contribution to every modal energy derivative vanishes
exactly.  This statement uses the actual repository transport operator. -/
theorem meanSpectralTransport_energy_re_eq_zero
    (u : WeightedLatticeBanach) (hu : PhysicalAntiHermitian u)
    (m : LatticeMode) (w : ComplexSpace) :
    (inner ℂ (complexEuclideanPoint w)
      (complexEuclideanPoint
        (spectralTransport (latticeFrequency m)
          (weightedLatticeCoefficient u (0 : LatticeMode)) w))).re = 0 := by
  rw [show complexEuclideanPoint
      (spectralTransport (latticeFrequency m)
        (weightedLatticeCoefficient u (0 : LatticeMode)) w) =
      (inner ℂ (complexFrequency (latticeFrequency m))
        (complexEuclideanPoint
          (weightedLatticeCoefficient u (0 : LatticeMode)))) •
        complexEuclideanPoint w by
    simp [spectralTransport, complexEuclideanPoint_smul]]
  rw [inner_smul_right, Complex.mul_re]
  have hwim : (inner ℂ (complexEuclideanPoint w)
      (complexEuclideanPoint w)).im = 0 := by
    simpa using (inner_self_im (𝕜 := ℂ) (complexEuclideanPoint w))
  rw [meanTransportScalar_re_eq_zero u hu m, hwim]
  ring_nf

/-- Exact scalar flow generated by transport against the conserved physical
zero coefficient. -/
def physicalMeanDriftMultiplier
    (u : WeightedLatticeBanach) (m : LatticeMode) (t : ℝ) : ℂ :=
  Complex.exp
    ((t : ℂ) * inner ℂ (complexFrequency (latticeFrequency m))
      (complexEuclideanPoint
        (weightedLatticeCoefficient u (0 : LatticeMode))))

/-- A physical mean generates a unit-modulus phase at every mode and time. -/
theorem norm_physicalMeanDriftMultiplier
    (u : WeightedLatticeBanach) (hu : PhysicalAntiHermitian u)
    (m : LatticeMode) (t : ℝ) :
    ‖physicalMeanDriftMultiplier u m t‖ = 1 := by
  unfold physicalMeanDriftMultiplier
  rw [Complex.norm_exp]
  have hs := meanTransportScalar_re_eq_zero u hu m
  rw [Complex.mul_re, Complex.ofReal_re, Complex.ofReal_im, zero_mul,
    sub_zero, hs, mul_zero, Real.exp_zero]

/-- The exact physical mean-drift orbit preserves the Hermitian modal
amplitude. -/
theorem complexEuclideanNorm_physicalMeanDriftOrbit
    (u : WeightedLatticeBanach) (hu : PhysicalAntiHermitian u)
    (m : LatticeMode) (t : ℝ) (w : ComplexSpace) :
    complexEuclideanNorm (physicalMeanDriftMultiplier u m t • w) =
      complexEuclideanNorm w := by
  unfold complexEuclideanNorm
  rw [complexEuclideanPoint_smul, norm_smul,
    norm_physicalMeanDriftMultiplier u hu m t, one_mul]

/-- Exact multiplier for viscosity plus transport by the physical zero mode. -/
def physicalMeanViscousMultiplier
    (μ : ℝ) (u : WeightedLatticeBanach) (m : LatticeMode) (t : ℝ) : ℂ :=
  Complex.exp
    ((t : ℂ) *
      (((-μ * ‖complexFrequency (latticeFrequency m)‖ ^ 2 : ℝ) : ℂ) +
        inner ℂ (complexFrequency (latticeFrequency m))
          (complexEuclideanPoint
            (weightedLatticeCoefficient u (0 : LatticeMode)))))

/-- Once viscosity is included, a physical mean changes only phase: the
modal amplitude is exactly the heat amplitude. -/
theorem norm_physicalMeanViscousMultiplier
    (μ : ℝ) (u : WeightedLatticeBanach) (hu : PhysicalAntiHermitian u)
    (m : LatticeMode) (t : ℝ) :
    ‖physicalMeanViscousMultiplier μ u m t‖ =
      Real.exp ((-μ * ‖complexFrequency (latticeFrequency m)‖ ^ 2) * t) := by
  unfold physicalMeanViscousMultiplier
  rw [Complex.norm_exp]
  have hs := meanTransportScalar_re_eq_zero u hu m
  rw [Complex.mul_re, Complex.ofReal_re, Complex.ofReal_im, zero_mul,
    sub_zero, Complex.add_re, hs]
  congr 1
  norm_cast
  ring_nf

/-- For nonnegative viscosity and forward time, the combined physical
mean-plus-heat flow is a modal contraction. -/
theorem complexEuclideanNorm_physicalMeanViscousOrbit_le
    (μ : ℝ) (hμ : 0 ≤ μ) (u : WeightedLatticeBanach)
    (hu : PhysicalAntiHermitian u) (m : LatticeMode) (t : ℝ) (ht : 0 ≤ t)
    (w : ComplexSpace) :
    complexEuclideanNorm (physicalMeanViscousMultiplier μ u m t • w) ≤
      complexEuclideanNorm w := by
  unfold complexEuclideanNorm
  rw [complexEuclideanPoint_smul, norm_smul,
    norm_physicalMeanViscousMultiplier μ u hu m t]
  have hexp : Real.exp
      ((-μ * ‖complexFrequency (latticeFrequency m)‖ ^ 2) * t) ≤ 1 := by
    rw [← Real.exp_zero]
    apply Real.exp_le_exp.mpr
    exact mul_nonpos_of_nonpos_of_nonneg
      (mul_nonpos_of_nonpos_of_nonneg (neg_nonpos.mpr hμ) (sq_nonneg _)) ht
  exact mul_le_of_le_one_left (norm_nonneg _) hexp

/-! ## Exact physical triad energy cancellation -/

/-- The complex-bilinear coordinate pairing which appears after using the
anti-Hermitian output relation in a Hermitian energy pairing. -/
def complexBilinearPairing (z w : ComplexSpace) : ℂ :=
  ∑ a : Fin 3, z a * w a

/-- Putting a negated conjugate in the first Hermitian slot exposes the
negative complex-bilinear pairing. -/
theorem inner_neg_complexConjugate_left
    (z w : ComplexSpace) :
    inner ℂ (complexEuclideanPoint (-complexConjugate z))
      (complexEuclideanPoint w) = -complexBilinearPairing z w := by
  rw [EuclideanSpace.inner_toLp_toLp]
  simp [complexEuclideanPoint, complexConjugate, complexBilinearPairing,
    dotProduct]
  apply Finset.sum_congr rfl
  intro a ha
  exact mul_comm _ _

/-- The bilinear coordinate pairing is symmetric. -/
theorem complexBilinearPairing_comm (z w : ComplexSpace) :
    complexBilinearPairing z w = complexBilinearPairing w z := by
  unfold complexBilinearPairing
  simp_rw [mul_comm]

/-- Real energy transfer contributed by one ordered Fourier triad to its
output mode.  This uses the repository's literal `spectralTransport`. -/
def physicalTriadEnergy
    (u : WeightedLatticeBanach) (i j : LatticeMode) : ℝ :=
  (inner ℂ
    (complexEuclideanPoint (weightedLatticeCoefficient u (i + j)))
    (complexEuclideanPoint
      (spectralTransport (latticeFrequency j)
        (weightedLatticeCoefficient u i)
        (weightedLatticeCoefficient u j)))).re

/-- Under physical reality, a triad energy contribution can be written with
the third member `l = -i-j` and a bilinear output pairing. -/
theorem physicalTriadEnergy_eq
    (u : WeightedLatticeBanach) (hu : PhysicalAntiHermitian u)
    (i j l : LatticeMode) (hijl : i + j + l = 0) :
    physicalTriadEnergy u i j =
      (-((inner ℂ (complexFrequency (latticeFrequency j))
          (complexEuclideanPoint (weightedLatticeCoefficient u i))) *
        complexBilinearPairing
          (weightedLatticeCoefficient u l)
          (weightedLatticeCoefficient u j))).re := by
  have hout : i + j = -l := by
    apply eq_neg_of_add_eq_zero_left
    exact hijl
  unfold physicalTriadEnergy spectralTransport
  rw [hout, hu l, complexEuclideanPoint_smul, inner_smul_right,
    inner_neg_complexConjugate_left]
  ring_nf

/-- Exact pairwise cancellation of physical nonlinear energy transfer.  For
the zero-sum triple `i+j+l=0`, swapping the transported mode `j` with `l`
cancels the two real transfers.  This is the local algebra behind the global
Galerkin energy identity, and it holds at arbitrary amplitude. -/
theorem physicalTriadEnergy_pair_cancel
    (u : WeightedLatticeBanach) (hphysical : PhysicalAntiHermitian u)
    (hdiv : CriticalMildDuhamelBochner.LatticeDivergenceFree u)
    (i j l : LatticeMode) (hijl : i + j + l = 0) :
    physicalTriadEnergy u i j + physicalTriadEnergy u i l = 0 := by
  rw [physicalTriadEnergy_eq u hphysical i j l hijl]
  have hilj : i + l + j = 0 := by
    calc
      i + l + j = i + j + l := by ac_rfl
      _ = 0 := hijl
  rw [physicalTriadEnergy_eq u hphysical i l j hilj]
  rw [complexBilinearPairing_comm
    (weightedLatticeCoefficient u j) (weightedLatticeCoefficient u l)]
  have hfreq : complexFrequency (latticeFrequency j) +
      complexFrequency (latticeFrequency l) =
      -complexFrequency (latticeFrequency i) := by
    have hsum : j + l + i = 0 := by
      calc
        j + l + i = i + j + l := by ac_rfl
        _ = 0 := hijl
    have hjl : j + l = -i := eq_neg_of_add_eq_zero_left hsum
    rw [← CriticalMildDuhamelBochner.complexFrequency_latticeFrequency_add,
      hjl]
    ext a
    fin_cases a <;>
      simp [latticeFrequency, complexFrequency, complexEuclideanPoint,
        complexOfReal, complexOfParts]
  have hscalar :
      inner ℂ (complexFrequency (latticeFrequency j))
          (complexEuclideanPoint (weightedLatticeCoefficient u i)) +
        inner ℂ (complexFrequency (latticeFrequency l))
          (complexEuclideanPoint (weightedLatticeCoefficient u i)) = 0 := by
    rw [← inner_add_left, hfreq, inner_neg_left, hdiv i, neg_zero]
  have hsumprod :
      (inner ℂ (complexFrequency (latticeFrequency j))
          (complexEuclideanPoint (weightedLatticeCoefficient u i))) *
          complexBilinearPairing (weightedLatticeCoefficient u l)
            (weightedLatticeCoefficient u j) +
        (inner ℂ (complexFrequency (latticeFrequency l))
          (complexEuclideanPoint (weightedLatticeCoefficient u i))) *
          complexBilinearPairing (weightedLatticeCoefficient u l)
            (weightedLatticeCoefficient u j) = 0 := by
    rw [← add_mul, hscalar, zero_mul]
  have hre := congrArg Complex.re hsumprod
  simp only [Complex.add_re, Complex.zero_re] at hre
  change
    -(inner ℂ (complexFrequency (latticeFrequency j))
        (complexEuclideanPoint (weightedLatticeCoefficient u i)) *
          complexBilinearPairing (weightedLatticeCoefficient u l)
            (weightedLatticeCoefficient u j)).re +
      -(inner ℂ (complexFrequency (latticeFrequency l))
        (complexEuclideanPoint (weightedLatticeCoefficient u i)) *
          complexBilinearPairing (weightedLatticeCoefficient u l)
            (weightedLatticeCoefficient u j)).re = 0
  linarith

/-- The actual Leray projection at an output mode does not change its energy
pairing with a divergence-free coefficient at that mode. -/
theorem inner_output_complexLeray_eq
    (u : WeightedLatticeBanach)
    (hdiv : CriticalMildDuhamelBochner.LatticeDivergenceFree u)
    (k : LatticeMode) (z : ComplexSpace) :
    inner ℂ (complexEuclideanPoint (weightedLatticeCoefficient u k))
        (complexEuclideanPoint (complexLeray (latticeFrequency k) z)) =
      inner ℂ (complexEuclideanPoint (weightedLatticeCoefficient u k))
        (complexEuclideanPoint z) := by
  rw [complexEuclideanPoint_complexLeray, complexEuclideanLeray_formula,
    inner_sub_right, inner_smul_right]
  have hright : inner ℂ
      (complexEuclideanPoint (weightedLatticeCoefficient u k))
      (complexFrequency (latticeFrequency k)) = 0 := by
    rw [← inner_conj_symm]
    simp [hdiv k]
  rw [hright, mul_zero, sub_zero]

/-- Real energy transfer from the actual projected transport term at one
ordered triad. -/
def projectedPhysicalTriadEnergy
    (u : WeightedLatticeBanach) (i j : LatticeMode) : ℝ :=
  (inner ℂ
    (complexEuclideanPoint (weightedLatticeCoefficient u (i + j)))
    (complexEuclideanPoint
      (complexLeray (latticeFrequency (i + j))
        (spectralTransport (latticeFrequency j)
          (weightedLatticeCoefficient u i)
          (weightedLatticeCoefficient u j))))).re

/-- The output Leray projection leaves each divergence-free triad energy
contribution unchanged. -/
theorem projectedPhysicalTriadEnergy_eq
    (u : WeightedLatticeBanach)
    (hdiv : CriticalMildDuhamelBochner.LatticeDivergenceFree u)
    (i j : LatticeMode) :
    projectedPhysicalTriadEnergy u i j = physicalTriadEnergy u i j := by
  unfold projectedPhysicalTriadEnergy physicalTriadEnergy
  rw [inner_output_complexLeray_eq u hdiv (i + j)]

/-- Pairwise cancellation therefore holds for the repository's full
frequencywise projected nonlinearity, not merely for its unprojected
representative. -/
theorem projectedPhysicalTriadEnergy_pair_cancel
    (u : WeightedLatticeBanach) (hphysical : PhysicalAntiHermitian u)
    (hdiv : CriticalMildDuhamelBochner.LatticeDivergenceFree u)
    (i j l : LatticeMode) (hijl : i + j + l = 0) :
    projectedPhysicalTriadEnergy u i j +
      projectedPhysicalTriadEnergy u i l = 0 := by
  rw [projectedPhysicalTriadEnergy_eq u hdiv i j,
    projectedPhysicalTriadEnergy_eq u hdiv i l]
  exact physicalTriadEnergy_pair_cancel u hphysical hdiv i j l hijl

end Navier.Analysis.PhysicalPeriodicGlobalControl
