import Navier.ClayFrontier
import Navier.Analysis.CKNIntegralScaling
import Navier.Analysis.EnergyNormBridge
import Navier.Analysis.EnergyOfficialClause
import Navier.Analysis.FrequencyHeatLeray
import Navier.Analysis.ComplexLerayProjection
import Navier.Analysis.ComplexLerayNorm
import Navier.Analysis.ComplexFrequencyHeatLeray
import Navier.Analysis.EnergyConvectionCancellation
import Navier.Analysis.EnergyConvectionIntegral
import Navier.Analysis.EnergyTimeDerivative
import Navier.Analysis.EnergyViscousDissipation
import Navier.Analysis.EnergyViscousIntegral
import Navier.Analysis.EnergyPointwiseBalance
import Navier.Analysis.EnergyInstantaneousIntegralBalance
import Navier.Analysis.EnergyDerivativeUnderIntegral
import Navier.Routes.R7.GeneratedSupport
import Navier.Routes.R7.FiniteConvolution
import Navier.Routes.R7.FiniteAmplitudeDynamics
import Navier.Routes.R7.FiniteReality
import Navier.Routes.R7.FiniteSupportClosureObstruction
import Navier.Routes.R7.GeneratedSupportStrictGrowth
import Navier.OfficialProblem
import Navier.OfficialSurfaceSignatures
import Navier.Analysis.Covariance
import Navier.Analysis.CriticalL3
import Navier.Analysis.CriticalL3Integrable
import Navier.Analysis.CriticalLp
import Navier.Analysis.CriticalProfileAction
import Navier.Analysis.ESSInputs
import Navier.Analysis.CKNCylinderGeometry
import Navier.Analysis.CKNMeasureTransport
import Navier.Analysis.CKNDensity
import Navier.Analysis.OfficialABEncoding
import Navier.Analysis.LerayProjection
import Navier.Analysis.VectorCalculus
import Navier.Analysis.EnergyPressureCancellation
import Navier.Analysis.EnergyPressureIntegral
import Navier.Analysis.Vorticity
import Navier.Analysis.ViscosityTransport
import Navier.Analysis.ViscosityAdmissibility
import Navier.Analysis.ViscosityForceDecay
import Navier.Analysis.ViscosityEndpoints
import Navier.EnergyObstruction
import Navier.ConventionBridges
import Navier.Breakdown.MaximalNonextension
import Navier.Breakdown.Restriction
import Navier.Breakdown.ForceRecovery
import Navier.Breakdown.OfficialCDEncoding
import Navier.Routes.R7.ExactSymbol
import Navier.Routes.R7.Triad
import Navier.Routes.R7.ScaledTriad
import Navier.Routes.R7.PhaseSymbol
import Navier.Routes.R7.SymmetrizedPhase
import Navier.Routes.R7.SymmetrizedWitness
import Navier.Routes.R7.WeightedShellTransfer
import Navier.Routes.R7.FieldLeakage
import Navier.Routes.R7.FullFieldLeakage
import Navier.Routes.R7.FullSixModePairClassification
import Navier.Routes.R7.FullSixModeReceiverRates
import Navier.Routes.R7.FullSixModeBalance

/-!
# Raw axiom audit for the public formal infrastructure

Each command below asks Lean for the transitive axioms of a named declaration.
The resumed section below covers every public theorem added by the local,
energy, CKN-scaling, and generated-frequency attack leaves.  The audit of
`Clay.StatementA` concerns only the canonical proposition's
definition and its imported foundations; it does not construct an inhabitant
and is not evidence that the conjectural endpoint is proved.  The proved
declarations audited below are scaling arithmetic, disposition guards, and
finite-frontier facts.
-/

#print axioms Navier.Clay.StatementA
#print axioms Navier.Clay.StatementB
#print axioms Navier.Clay.StatementC
#print axioms Navier.Clay.StatementD
#print axioms Navier.problemEncodingResiduals_card
#print axioms Navier.OfficialSurfaceSignatures.classicalSolution_signature
#print axioms Navier.OfficialSurfaceSignatures.periodicClassicalSolution_signature
#print axioms Navier.OfficialSurfaceSignatures.statementA_signature
#print axioms Navier.OfficialSurfaceSignatures.statementB_signature
#print axioms Navier.OfficialSurfaceSignatures.statementC_signature
#print axioms Navier.OfficialSurfaceSignatures.statementD_signature

#print axioms Navier.Scaling.mixedNormExponent_eq_zero_iff
#print axioms Navier.Scaling.criticalLine_six_four
#print axioms Navier.Scaling.criticalLine_nine_three
#print axioms Navier.Scaling.reciprocalMixedNormExponent_eq_zero_iff
#print axioms Navier.Scaling.reciprocalCriticalLine_three_infinity
#print axioms Navier.Scaling.reciprocalCriticalLine_infinity_two

#print axioms Navier.EnergyObstruction.space_finrank
#print axioms Navier.EnergyObstruction.l2_energy_dilation
#print axioms Navier.EnergyObstruction.l3_critical_dilation
#print axioms Navier.EnergyObstruction.energy_not_scale_coercive
#print axioms Navier.EnergyObstruction.lp_dilation_scaling
#print axioms Navier.EnergyObstruction.time_dilation_scaling

#print axioms Navier.ConventionBridges.schwartzmap_satisfies_fefferman_rapid_decay
#print axioms Navier.ConventionBridges.schwartzmap_satisfies_fefferman_smoothness

#print axioms Navier.staticDivergence_smul
#print axioms Navier.staticDivergence_const_smul
#print axioms Navier.convection_eq_sum_coordinate_derivatives
#print axioms Navier.pressure_work_eq_staticDivergence
#print axioms Navier.Analysis.EnergyPressureIntegral.integral_staticDivergence_eq_zero
#print axioms Navier.Analysis.EnergyPressureIntegral.integral_pressure_work_eq_zero

#print axioms Navier.Analysis.Vorticity.staticCurl_dilation
#print axioms Navier.Analysis.Vorticity.vorticity_scaled
#print axioms Navier.Analysis.Vorticity.officialEuclideanNorm_eq_zero_iff
#print axioms Navier.Analysis.Vorticity.officialEuclideanNorm_smul
#print axioms Navier.Analysis.Vorticity.vorticityDirection_euclideanNorm

#print axioms Navier.Analysis.Covariance.fderiv_velocity_dilation
#print axioms Navier.Analysis.Covariance.staticDivergence_dilation
#print axioms Navier.Analysis.Covariance.zero_dilation_truth_check
#print axioms Navier.Analysis.Covariance.scaledSchwartzVelocity_apply
#print axioms Navier.Analysis.Covariance.divergenceFreeInitial_scaled
#print axioms Navier.Analysis.Covariance.fderiv_amplitude_dilation
#print axioms Navier.Analysis.Covariance.spatialDerivative_scaled
#print axioms Navier.Analysis.Covariance.divergence_scaled
#print axioms Navier.Analysis.Covariance.convection_scaled
#print axioms Navier.Analysis.Covariance.pressureGradient_scaled
#print axioms Navier.Analysis.Covariance.secondDirectionalDerivative_scaled
#print axioms Navier.Analysis.Covariance.laplacian_scaled
#print axioms Navier.Analysis.Covariance.timeDerivative_scaled
#print axioms Navier.Analysis.Covariance.satisfiesNavierStokes_scaled
#print axioms Navier.Analysis.Covariance.zero_scale_fields
#print axioms Navier.Analysis.Covariance.one_scale_fields

#print axioms Navier.Analysis.CriticalL3.criticalL3Mass_parabolicScaled
#print axioms Navier.Analysis.CriticalL3.criticalL3BoundOn_parabolicScaled_iff
#print axioms Navier.Analysis.CriticalL3.criticalL3BoundBefore_parabolicScaled_iff

#print axioms Navier.Analysis.CriticalL3Integrable.integrableCriticalL3BoundOn_to_raw
#print axioms Navier.Analysis.CriticalL3Integrable.l3SliceIntegrable_parabolicScaled_iff
#print axioms Navier.Analysis.CriticalL3Integrable.integrableCriticalL3BoundOn_parabolicScaled_iff
#print axioms Navier.Analysis.CriticalL3Integrable.integrableCriticalL3BoundBefore_parabolicScaled_iff

#print axioms Navier.Analysis.CriticalLp.memLp_three_iff_integrable_norm_cube
#print axioms Navier.Analysis.CriticalLp.aestronglyMeasurable_criticalL3SpatialScale_iff
#print axioms Navier.Analysis.CriticalLp.integrable_norm_cube_criticalL3SpatialScale_iff
#print axioms Navier.Analysis.CriticalLp.memLp_three_criticalL3SpatialScale_iff
#print axioms Navier.Analysis.CriticalLp.eLpNorm_three_criticalL3SpatialScale
#print axioms Navier.Analysis.CriticalLp.lpNorm_three_criticalL3SpatialScale
#print axioms Navier.Analysis.CriticalLp.memLp_three_iff_l3SliceIntegrable
#print axioms Navier.Analysis.CriticalLp.memLp_three_parabolicScaled_iff
#print axioms Navier.Analysis.CriticalLp.eLpNorm_three_parabolicScaled
#print axioms Navier.Analysis.CriticalLp.lpNorm_three_parabolicScaled
#print axioms Navier.Analysis.CriticalLp.criticalL3MemLpBoundOn_parabolicScaled_iff
#print axioms Navier.Analysis.CriticalLp.criticalL3MemLpBoundBefore_parabolicScaled_iff

#print axioms Navier.Analysis.CriticalProfileAction.criticalProfileAction_one_zero
#print axioms Navier.Analysis.CriticalProfileAction.criticalProfileAction_comp
#print axioms Navier.Analysis.CriticalProfileAction.criticalProfileAction_inverse_left
#print axioms Navier.Analysis.CriticalProfileAction.criticalProfileAction_inverse_right
#print axioms Navier.Analysis.CriticalProfileAction.criticalProfileAction_relative
#print axioms Navier.Analysis.CriticalProfileAction.criticalProfileAction_eq_scale_translate
#print axioms Navier.Analysis.CriticalProfileAction.memLp_criticalProfileTranslate_iff
#print axioms Navier.Analysis.CriticalProfileAction.eLpNorm_criticalProfileTranslate
#print axioms Navier.Analysis.CriticalProfileAction.memLp_three_criticalProfileAction_iff
#print axioms Navier.Analysis.CriticalProfileAction.eLpNorm_three_criticalProfileAction

#print axioms Navier.Analysis.ESSInputs.PartialClassicalSolution.velocity_slice_continuous
#print axioms Navier.Analysis.ESSInputs.PartialClassicalSolution.pressure_slice_continuous
#print axioms Navier.Analysis.ESSInputs.PartialClassicalSolution.velocity_slice_aestronglyMeasurable
#print axioms Navier.Analysis.ESSInputs.PartialClassicalSolution.pressure_slice_aestronglyMeasurable
#print axioms Navier.Analysis.ESSInputs.PartialClassicalSolution.velocity_slice_memLp_three_iff

#print axioms Navier.Analysis.CKNCylinder.parabolicPointEquiv_apply
#print axioms Navier.Analysis.CKNCylinder.parabolicPointMap_preimage_backwardEuclideanCylinder
#print axioms Navier.Analysis.CKNCylinder.parabolicPointMap_surjective
#print axioms Navier.Analysis.CKNCylinder.parabolicPointMap_image_backwardEuclideanCylinder
#print axioms Navier.Analysis.CKNCylinder.integrableOn_comp_parabolicPointMap_iff
#print axioms Navier.Analysis.CKNCylinder.integrableOn_const_mul_comp_backwardEuclideanCylinder_iff
#print axioms Navier.Analysis.CKNCylinder.velocityCubicDensity_parabolicScaled
#print axioms Navier.Analysis.CKNCylinder.sq_rpow_three_halves
#print axioms Navier.Analysis.CKNCylinder.pressureThreeHalvesDensity_parabolicScaled
#print axioms Navier.Analysis.CKNCylinder.cknDensity_parabolicScaled
#print axioms Navier.Analysis.CKNCylinder.velocityCubicIntegrableOn_parabolicScaled_iff
#print axioms Navier.Analysis.CKNCylinder.pressureThreeHalvesIntegrableOn_parabolicScaled_iff
#print axioms Navier.Analysis.CKNCylinder.cknDensityIntegrableOn_parabolicScaled_iff

#print axioms Navier.Analysis.OfficialABEncoding.officialEuclideanPoint_apply
#print axioms Navier.Analysis.OfficialABEncoding.officialEuclideanNorm_nonneg
#print axioms Navier.Analysis.OfficialABEncoding.officialEuclideanNorm_eq_sqrt_sum_sq
#print axioms Navier.Analysis.OfficialABEncoding.norm_le_officialEuclideanNorm
#print axioms Navier.Analysis.OfficialABEncoding.officialEuclideanNorm_le
#print axioms Navier.Analysis.OfficialABEncoding.feffermanRapidDecayBound_iff_euclideanWeight
#print axioms Navier.Analysis.OfficialABEncoding.schwartzmap_satisfies_fefferman_euclidean_weight_rapid_decay

#print axioms Navier.Analysis.LerayProjection.euclideanLeray_mem
#print axioms Navier.Analysis.LerayProjection.inner_euclideanLeray
#print axioms Navier.Analysis.LerayProjection.euclideanLeray_norm_le
#print axioms Navier.Analysis.LerayProjection.euclideanLeray_idempotent
#print axioms Navier.Analysis.LerayProjection.euclideanLeray_formula
#print axioms Navier.Analysis.LerayProjection.officialPoint_inner_eq_dotProduct
#print axioms Navier.Analysis.LerayProjection.officialPoint_norm_sq_eq_dotProduct
#print axioms Navier.Analysis.LerayProjection.officialPoint_normalizedLeray
#print axioms Navier.Analysis.LerayProjection.officialEuclideanNorm_normalizedLeray_le

#print axioms Navier.Analysis.ViscosityTransport.satisfiesNavierStokes_viscosityScaled_mul
#print axioms Navier.Analysis.ViscosityTransport.satisfiesNavierStokes_one_to_viscosity
#print axioms Navier.Analysis.ViscosityTransport.satisfiesNavierStokes_viscosity_to_one
#print axioms Navier.Analysis.ViscosityTransport.viscosityScaledForce_zero
#print axioms Navier.Analysis.ViscosityTransport.viscosityScaledVelocity_inv
#print axioms Navier.Analysis.ViscosityTransport.viscosityScaledForce_inv

#print axioms Navier.Analysis.ViscosityAdmissibility.isPeriodicClassicalSolution_viscosityScaled_mul
#print axioms Navier.Analysis.ViscosityAdmissibility.isClassicalSolution_viscosityScaled_mul
#print axioms Navier.Analysis.ViscosityAdmissibility.kineticEnergy_viscosityScaled
#print axioms Navier.Analysis.ViscosityAdmissibility.forcedDataRapidDecay_zeroForce
#print axioms Navier.Analysis.ViscosityAdmissibility.periodicForcedDataRapidDecay_zeroForce

#print axioms Navier.Analysis.ViscosityForceDecay.iteratedFDerivWithin_viscosityScaledForce
#print axioms Navier.Analysis.ViscosityForceDecay.forcedDataRapidDecay_viscosityScaled
#print axioms Navier.Analysis.ViscosityForceDecay.periodicForcedDataRapidDecay_viscosityScaled

#print axioms Navier.Analysis.ViscosityEndpoints.statementA_iff_atViscosityOne
#print axioms Navier.Analysis.ViscosityEndpoints.statementB_iff_atViscosityOne
#print axioms Navier.Analysis.ViscosityEndpoints.statementC_iff_atViscosityOne
#print axioms Navier.Analysis.ViscosityEndpoints.statementD_iff_atViscosityOne
#print axioms Navier.Analysis.ViscosityEndpoints.statementC_of_zeroForceAtViscosityOne
#print axioms Navier.Analysis.ViscosityEndpoints.statementD_of_zeroForceAtViscosityOne

#print axioms Navier.Breakdown.bounded_pointEvaluation_of_smooth
#print axioms Navier.Breakdown.noGlobal_of_pointEvaluationBreakdown
#print axioms Navier.Breakdown.noWholeSpaceGlobal_of_pointEvaluationBreakdown
#print axioms Navier.Breakdown.noPeriodicGlobal_of_pointEvaluationBreakdown

#print axioms Navier.Breakdown.spacetimeBefore_mono
#print axioms Navier.Breakdown.PartialClassicalSolution.restrict
#print axioms Navier.Breakdown.PartialClassicalSolution.restrict_velocity
#print axioms Navier.Breakdown.PartialClassicalSolution.restrict_pressure
#print axioms Navier.Breakdown.PartialClassicalSolution.restrict_restrict
#print axioms Navier.Breakdown.velocityAgreesBefore_refl
#print axioms Navier.Breakdown.velocityAgreesBefore_symm
#print axioms Navier.Breakdown.velocityAgreesBefore_trans
#print axioms Navier.Breakdown.velocityAgreesBefore_mono

#print axioms Navier.Breakdown.ForceRecovery.recoveredForce
#print axioms Navier.Breakdown.ForceRecovery.satisfiesNavierStokes_iff_force_eq_recoveredForce
#print axioms Navier.Breakdown.ForceRecovery.satisfiesNavierStokesBefore_iff_force_eq_recoveredForce
#print axioms Navier.Breakdown.PartialClassicalSolution.ofClassical
#print axioms Navier.Breakdown.zeroPartialClassicalSolution
#print axioms Navier.Breakdown.zeroPartial_not_pointNormUnbounded

#print axioms Navier.Breakdown.OfficialCDEncoding.norm_le_euclideanNorm
#print axioms Navier.Breakdown.OfficialCDEncoding.euclideanNorm_le_sqrt_three_mul_norm
#print axioms Navier.Breakdown.OfficialCDEncoding.abs_coordinateForceDerivativeWithin_le
#print axioms Navier.Breakdown.OfficialCDEncoding.forcedDataRapidDecay_implies_coordinatewise
#print axioms Navier.Breakdown.OfficialCDEncoding.periodicForcedDataRapidDecay_implies_coordinatewise

#print axioms Navier.Routes.R7.dot_lerayNumerator
#print axioms Navier.Routes.R7.divergenceFree_singleMode_selfInteraction_zero
#print axioms Navier.Routes.R7.countermodel_energyCancellation
#print axioms Navier.Routes.R7.countermodel_witness_value
#print axioms Navier.Routes.R7.countermodel_selfInteraction_ne_zero

#print axioms Navier.Routes.R7.receiver_dot_lerayNumerator
#print axioms Navier.Routes.R7.advector_pair_cancels
#print axioms Navier.Routes.R7.grouped_six_transfer_cancellation
#print axioms Navier.Routes.R7.six_transfer_sum_zero
#print axioms Navier.Routes.R7.witness_admissible
#print axioms Navier.Routes.R7.witness_nontermwise_cancellation

#print axioms Navier.Routes.R7.scaled_witness_admissible
#print axioms Navier.Routes.R7.scaled_witness_orderedTransfer
#print axioms Navier.Routes.R7.scaled_witness_sixTransferSum
#print axioms Navier.Routes.R7.orderedTransfer_unbounded_across_scale

#print axioms Navier.Routes.R7.normalizedLeraySymbol_zero
#print axioms Navier.Routes.R7.receiver_dot_normalizedLeraySymbol
#print axioms Navier.Routes.R7.normalizedProjectedOrderedCoefficient_eq_orderedTransfer
#print axioms Navier.Routes.R7.receiver_orthogonal_output_of_triad
#print axioms Navier.Routes.R7.phasedNormalizedProjectedCoefficient_eq_ordered
#print axioms Navier.Routes.R7.unphased_witness_real_part_zero
#print axioms Navier.Routes.R7.phased_witness_orderedCoefficient
#print axioms Navier.Routes.R7.witness_phase_factors_have_unit_norm
#print axioms Navier.Routes.R7.witness_receiver_orthogonal_output
#print axioms Navier.Routes.R7.phased_normalized_witness_coefficient
#print axioms Navier.Routes.R7.witness_opposite_orderedCoefficient
#print axioms Navier.Routes.R7.scaled_witness_receiver_orthogonal_output
#print axioms Navier.Routes.R7.phased_scaled_normalized_coefficient
#print axioms Navier.Routes.R7.phased_normalized_coefficient_unbounded_across_positive_scale

#print axioms Navier.Routes.R7.phased_symmetrized_scaled_witness_cancels
#print axioms Navier.Routes.R7.no_scaled_witness_nonzero_symmetrized_output

#print axioms Navier.Routes.R7.sym_scaled_witness_admissible
#print axioms Navier.Routes.R7.phased_symmetrized_scaled_witness_coefficient
#print axioms Navier.Routes.R7.phased_symmetrized_coefficient_unbounded_across_positive_scale
#print axioms Navier.Routes.R7.symWitnessModeCoefficient_conjugate
#print axioms Navier.Routes.R7.symWitnessMode_divergence_free

#print axioms Navier.Routes.R7.symWitnessRateK_eq_zero
#print axioms Navier.Routes.R7.symWitnessRateL_eq_neg
#print axioms Navier.Routes.R7.symWitnessRateM_eq
#print axioms Navier.Routes.R7.symWitness_constantWeight_cancels
#print axioms Navier.Routes.R7.symWitnessSquaredFrequencyRate_eq_cube
#print axioms Navier.Routes.R7.symWitnessSquaredFrequencyRate_pos

#print axioms Navier.Routes.R7.phased_symmetrized_scaled_leak_coefficient
#print axioms Navier.Routes.R7.leakOutputWave_not_in_six_mode_support
#print axioms Navier.Routes.R7.six_mode_support_has_nonzero_off_support_interaction

#print axioms Navier.Routes.R7.pairProducesLeakOutput_iff
#print axioms Navier.Routes.R7.fullSixModeProjectedLeakCoefficient_eq_scale
#print axioms Navier.Routes.R7.fullSixMode_has_nonzero_off_support_coefficient

#print axioms Navier.Routes.R7.pairProducesModeOutput_iff
#print axioms Navier.Routes.R7.sum_symWitnessMode
#print axioms Navier.Routes.R7.symWitnessModeAmplitude_transverse_scaled
#print axioms Navier.Routes.R7.fullSixModeReceiverRate_eq_orderedRate
#print axioms Navier.Routes.R7.fullSixModeReceiverRate_eq
#print axioms Navier.Routes.R7.fullSixModeEnergyRate_eq_zero
#print axioms Navier.Routes.R7.fullSixModeSquaredFrequencyRate_eq_two_cubes
#print axioms Navier.Routes.R7.fullSixModeSquaredFrequencyRate_pos
#print axioms Navier.Routes.R7.fullSixModeBalance

#print axioms Navier.ScientificDisposition.readiness_realized
#print axioms Navier.ScientificDisposition.readiness_falsified
#print axioms Navier.ScientificDisposition.readiness_conditional
#print axioms Navier.ScientificDisposition.readiness_conjectural
#print axioms Navier.ScientificDisposition.readiness_quarantined
#print axioms Navier.ScientificDisposition.readiness_eq_true_iff_status_eq_realized
#print axioms Navier.ScientificDisposition.readiness_eq_false_iff_status_ne_realized
#print axioms Navier.ScientificDisposition.proof_of_readiness
#print axioms Navier.ScientificDisposition.nonrealized_cannot_be_ready
#print axioms Navier.scientificStatus_card

#print axioms Navier.Frontier.dependency_rank_decreases
#print axioms Navier.Frontier.not_mem_own_dependencies
#print axioms Navier.Frontier.nodes_card
#print axioms Navier.Frontier.encodingResidual_is_tracked
#print axioms Navier.Frontier.statementA_dependencies

#print axioms Navier.Clay.statementADisposition_status
#print axioms Navier.Clay.statementADisposition_not_ready
#print axioms Navier.Clay.statementAFrontier_eq
#print axioms Navier.Clay.statementA_not_self_dependent

/-!
## Resumed full-map support leaves

Every public theorem introduced by the resumed local, energy, CKN-scaling,
and generated-frequency leaves is audited directly here so the canonical
`lake env lean Navier/AxiomAudit.lean` command emits the complete raw receipt.
These are support theorems, not inhabitants of an official Clay endpoint.
-/

#print axioms Navier.Analysis.CKNCylinder.det_parabolicPointEquiv
#print axioms Navier.Analysis.CKNCylinder.map_parabolicPointEquiv_spaceTimeVolume
#print axioms Navier.Analysis.CKNCylinder.setIntegral_comp_parabolicPointMap
#print axioms Navier.Analysis.CKNCylinder.setIntegral_comp_parabolicPointMap_backwardEuclideanCylinder
#print axioms Navier.Analysis.CKNCylinder.cknDensityIntegral_parabolicScaled
#print axioms Navier.Analysis.CKNCylinder.normalizedCKNFunctional_parabolicScaled
#print axioms Navier.Analysis.EnergyNormBridge.continuous_officialEuclideanNorm
#print axioms Navier.Analysis.EnergyNormBridge.norm_sq_le_officialEuclideanNorm_sq
#print axioms Navier.Analysis.EnergyNormBridge.officialEuclideanNorm_sq_le_three_mul_norm_sq
#print axioms Navier.Analysis.EnergyNormBridge.integrable_norm_sq_iff_officialEuclideanNorm_sq
#print axioms Navier.Analysis.EnergyNormBridge.kineticEnergy_le_officialKineticEnergy
#print axioms Navier.Analysis.EnergyNormBridge.officialKineticEnergy_le_three_mul_kineticEnergy
#print axioms Navier.Analysis.EnergyNormBridge.uniformlyBoundedEnergy_iff_official
#print axioms Navier.Analysis.EnergyOfficialClause.officialEuclideanNorm_sq_eq_sum_sq
#print axioms Navier.Analysis.EnergyOfficialClause.officialKineticEnergy_eq_coordinateKineticEnergy
#print axioms Navier.Analysis.EnergyOfficialClause.officialWholeSpaceEnergyClause_iff_coordinate
#print axioms Navier.Analysis.EnergyOfficialClause.currentWholeSpaceEnergyClause_iff_official
#print axioms Navier.Analysis.EnergyOfficialClause.IsClassicalSolution.velocity_slice_continuous
#print axioms Navier.Analysis.EnergyOfficialClause.IsClassicalSolution.velocity_slice_aestronglyMeasurable
#print axioms Navier.Analysis.EnergyOfficialClause.IsClassicalSolution.officialWholeSpaceEnergyClause
#print axioms Navier.Analysis.EnergyOfficialClause.IsClassicalSolution.coordinateWholeSpaceEnergyClause
#print axioms Navier.Analysis.FrequencyHeatLeray.frequencyHeatLeray_apply
#print axioms Navier.Analysis.FrequencyHeatLeray.frequencyHeatLeray_zero_time
#print axioms Navier.Analysis.FrequencyHeatLeray.frequencyHeatLeray_zero_frequency
#print axioms Navier.Analysis.FrequencyHeatLeray.frequencyHeatLeray_transverse
#print axioms Navier.Analysis.FrequencyHeatLeray.heatDecay_nonneg
#print axioms Navier.Analysis.FrequencyHeatLeray.heatDecay_le_one
#print axioms Navier.Analysis.FrequencyHeatLeray.frequencyHeatLeray_norm_le
#print axioms Navier.Analysis.FrequencyHeatLeray.frequencyHeatLeray_semigroup
#print axioms Navier.Analysis.ComplexLerayProjection.complexOfParts_apply
#print axioms Navier.Analysis.ComplexLerayProjection.complexOfParts_re
#print axioms Navier.Analysis.ComplexLerayProjection.complexOfParts_im
#print axioms Navier.Analysis.ComplexLerayProjection.complexOfParts_real_imaginary
#print axioms Navier.Analysis.ComplexLerayProjection.realPart_add
#print axioms Navier.Analysis.ComplexLerayProjection.imaginaryPart_add
#print axioms Navier.Analysis.ComplexLerayProjection.realPart_smul
#print axioms Navier.Analysis.ComplexLerayProjection.imaginaryPart_smul
#print axioms Navier.Analysis.ComplexLerayProjection.realPart_complexConjugate
#print axioms Navier.Analysis.ComplexLerayProjection.imaginaryPart_complexConjugate
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_add
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_sub
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_smul
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_neg
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_zero_vector
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_transverse
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_idempotent
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_apply
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_re
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_im
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_ofReal
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_zero_frequency
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_conjugate
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_idempotent
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_transverse
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanPoint_apply
#print axioms Navier.Analysis.ComplexLerayNorm.complexFrequency_apply
#print axioms Navier.Analysis.ComplexLerayNorm.complexFrequency_zero
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanLeray_mem
#print axioms Navier.Analysis.ComplexLerayNorm.inner_complexEuclideanLeray
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanLeray_norm_le
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanLeray_idempotent
#print axioms Navier.Analysis.ComplexLerayNorm.inner_complexFrequency
#print axioms Navier.Analysis.ComplexLerayNorm.complexFrequency_norm_sq
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanLeray_formula
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanLeray_zero_frequency
#print axioms Navier.Analysis.ComplexLerayNorm.complexBilinearDot_parts
#print axioms Navier.Analysis.ComplexLerayNorm.complex_division_of_parts
#print axioms Navier.Analysis.ComplexLerayNorm.complexLeray_formula
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanPoint_complexLeray
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanNorm_complexLeray_le
#print axioms Navier.Analysis.ComplexLerayNorm.complexLeray_hermitian_transverse
#print axioms Navier.Analysis.ComplexLerayNorm.complexLeray_bilinear_transverse_smoke
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanPoint_injective
#print axioms Navier.Analysis.ComplexLerayNorm.complexLeray_idempotent_smoke
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_apply
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_apply_coordinate
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_coordinate_formula
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexEuclideanPoint_smul
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_zero_time
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_zero_frequency
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexHeatDecay_nonneg
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexHeatDecay_le_one
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexEuclideanPoint_complexFrequencyHeatLeray
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_hermitian_transverse
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_bilinear_transverse
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexEuclideanNorm_complexFrequencyHeatLeray_le
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexHeatDecay_add
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_semigroup
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_conjugate
#print axioms Navier.differentiableAt_kineticEnergyDensity
#print axioms Navier.fderiv_kineticEnergyDensity
#print axioms Navier.staticGradient_kineticEnergyDensity
#print axioms Navier.convection_work_eq_staticDivergence
#print axioms Navier.convection_work_eq_staticDivergence_of_incompressible
#print axioms Navier.Analysis.EnergyConvectionIntegral.convection_work_integrand_eq_staticDivergence
#print axioms Navier.Analysis.EnergyConvectionIntegral.integral_convection_work_eq_zero
#print axioms Navier.differentiableWithinAt_timeSlice_of_smoothVelocity
#print axioms Navier.differentiableWithinAt_kineticEnergyDensity_time
#print axioms Navier.fderivWithin_kineticEnergyDensity_time
#print axioms Navier.kineticEnergyDensity_timeDerivative
#print axioms Navier.kineticEnergyDensity_timeDerivative_of_smoothVelocity
#print axioms Navier.kineticEnergyDensity_timeDerivative_eq_work
#print axioms Navier.kineticEnergyDensity_timeDerivative_eq_work_of_classicalSolution
#print axioms Navier.Analysis.EnergyViscousDissipation.derivativeEnergyDensity_nonneg
#print axioms Navier.Analysis.EnergyViscousDissipation.differentiableAt_viscousEnergyFlux
#print axioms Navier.Analysis.EnergyViscousDissipation.fderiv_viscousEnergyFlux_component
#print axioms Navier.Analysis.EnergyViscousDissipation.staticDivergence_viscousEnergyFlux
#print axioms Navier.Analysis.EnergyViscousDissipation.laplacian_work_eq_secondDerivative_sum
#print axioms Navier.Analysis.EnergyViscousDissipation.laplacian_work_eq_divergence_sub_derivativeEnergy
#print axioms Navier.Analysis.EnergyViscousDissipation.laplacian_work_add_derivativeEnergy_eq_divergence
#print axioms Navier.Analysis.EnergyViscousIntegral.differentiable_viscousEnergyFlux
#print axioms Navier.Analysis.EnergyViscousIntegral.integrable_staticDivergence_of_coordinatewise
#print axioms Navier.Analysis.EnergyViscousIntegral.integrable_laplacian_work_of_viscous_flux
#print axioms Navier.Analysis.EnergyViscousIntegral.integral_laplacian_work_eq_neg_derivativeEnergy
#print axioms Navier.Analysis.EnergyPointwiseBalance.contDiff_spatialSlice_of_smoothVelocity
#print axioms Navier.Analysis.EnergyPointwiseBalance.contDiff_spatialSlice_of_smoothPressure
#print axioms Navier.Analysis.EnergyPointwiseBalance.differentiable_coordinateDerivativeField_of_contDiff
#print axioms Navier.Analysis.EnergyPointwiseBalance.zeroForce_pointwise_energy_balance
#print axioms Navier.Analysis.EnergyPointwiseBalance.zeroForce_pointwise_energy_balance_of_classicalSolution
#print axioms Navier.Analysis.EnergyInstantaneousIntegralBalance.kineticEnergyDensity_timeDerivative_eq_zeroForce_work
#print axioms Navier.Analysis.EnergyInstantaneousIntegralBalance.integrable_pressure_work_of_flux
#print axioms Navier.Analysis.EnergyInstantaneousIntegralBalance.integrable_convection_work_of_flux
#print axioms Navier.Analysis.EnergyInstantaneousIntegralBalance.integrable_kineticEnergyDensity_timeDerivative_of_zeroForce
#print axioms Navier.Analysis.EnergyInstantaneousIntegralBalance.integral_kineticEnergyDensity_timeDerivative_eq_neg_viscousDissipation
#print axioms Navier.Analysis.EnergyDerivativeUnderIntegral.fderivWithin_integral_kineticEnergyDensity_eq_integral_of_dominated
#print axioms Navier.Routes.R7.subset_generatedSupportStep
#print axioms Navier.Routes.R7.add_mem_generatedSupportStep
#print axioms Navier.Routes.R7.generatedSupport_subset_succ
#print axioms Navier.Routes.R7.generatedSupport_mono
#print axioms Navier.Routes.R7.add_mem_generatedSupport_succ
#print axioms Navier.Routes.R7.scaledSymWitnessModeWave_mem_generatedSupport_zero
#print axioms Navier.Routes.R7.scaledSymWitnessModeWave_mem_generatedSupport
#print axioms Navier.Routes.R7.leakOutputWave_not_mem_generatedSupport_zero
#print axioms Navier.Routes.R7.leakOutputWave_eq_negK_add_posL
#print axioms Navier.Routes.R7.leakOutputWave_mem_generatedSupport_one
#print axioms Navier.Routes.R7.leakOutputWave_enters_at_generation_one
#print axioms Navier.Routes.R7.sixModeInitialSupport_centrallySymmetric
#print axioms Navier.Routes.R7.pairwiseMinkowskiSum_centrallySymmetric
#print axioms Navier.Routes.R7.generatedSupportStep_centrallySymmetric
#print axioms Navier.Routes.R7.generatedSupport_centrallySymmetric
#print axioms Navier.Routes.R7.complexBilinearDot_add_left
#print axioms Navier.Routes.R7.complexBilinearDot_add_right
#print axioms Navier.Routes.R7.complexBilinearDot_smul_left
#print axioms Navier.Routes.R7.complexBilinearDot_smul_right
#print axioms Navier.Routes.R7.complexWaveDot_add
#print axioms Navier.Routes.R7.complexWaveDot_smul
#print axioms Navier.Routes.R7.orderedConvectionCoefficient_add_advecting
#print axioms Navier.Routes.R7.orderedConvectionCoefficient_add_advected
#print axioms Navier.Routes.R7.orderedConvectionCoefficient_smul_advecting
#print axioms Navier.Routes.R7.orderedConvectionCoefficient_smul_advected
#print axioms Navier.Routes.R7.add_mem_pairwiseMinkowskiSum
#print axioms Navier.Routes.R7.finiteConvectionCoefficient_eq_zero_of_not_mem_pairwiseMinkowskiSum
#print axioms Navier.Routes.R7.projectedFiniteConvectionCoefficient_eq_zero_of_not_mem_pairwiseMinkowskiSum
#print axioms Navier.Routes.R7.projectedFiniteConvectionCoefficient_divergence
#print axioms Navier.Routes.R7.projectedFiniteConvectionCoefficient_already_projected
#print axioms Navier.Routes.R7.complexWaveDot_neg_wave
#print axioms Navier.Routes.R7.complexWaveDot_neg_amplitude
#print axioms Navier.Routes.R7.complexWaveDot_sub
#print axioms Navier.Routes.R7.squaredFrequency_zero
#print axioms Navier.Routes.R7.viscosityMultiplier_zero_frequency
#print axioms Navier.Routes.R7.viscousLinearRHS_zero_frequency
#print axioms Navier.Routes.R7.viscousLinearRHS_eq_zero_of_not_mem
#print axioms Navier.Routes.R7.finiteProjectedNonlinearRHS_eq_zero_of_not_mem_pairwiseMinkowskiSum
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_eq_zero_of_not_mem_generatedSupportStep
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_supportedOn_generatedSupportStep
#print axioms Navier.Routes.R7.finiteConvectionCoefficient_zero_output
#print axioms Navier.Routes.R7.projectedFiniteConvectionCoefficient_zero_output
#print axioms Navier.Routes.R7.finiteProjectedNonlinearRHS_zero_output
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_zero_output
#print axioms Navier.Routes.R7.viscousLinearRHS_divergence
#print axioms Navier.Routes.R7.finiteProjectedNonlinearRHS_divergence
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_divergence
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_modewiseDivergenceFree
#print axioms Navier.Routes.R7.coordinateConjugate_apply
#print axioms Navier.Routes.R7.coordinateConjugate_zero
#print axioms Navier.Routes.R7.coordinateConjugate_add
#print axioms Navier.Routes.R7.coordinateConjugate_neg
#print axioms Navier.Routes.R7.coordinateConjugate_smul
#print axioms Navier.Routes.R7.coordinateConjugate_involutive
#print axioms Navier.Routes.R7.coordinateConjugate_eq_complexConjugate
#print axioms Navier.Routes.R7.complexWaveDot_coordinateConjugate
#print axioms Navier.Routes.R7.normalizedLeraySymbol_neg_frequency
#print axioms Navier.Routes.R7.complexLeray_neg_frequency
#print axioms Navier.Routes.R7.complexLeray_neg_coordinateConjugate
#print axioms Navier.Routes.R7.orderedConvectionCoefficient_neg_coordinateConjugate
#print axioms Navier.Routes.R7.mem_support_neg_iff
#print axioms Navier.Routes.R7.pairSumsToOutput_neg_iff
#print axioms Navier.Routes.R7.coordinateConjugate_sum
#print axioms Navier.Routes.R7.finiteConvectionCoefficient_neg_output
#print axioms Navier.Routes.R7.projectedFiniteConvectionCoefficient_neg_output
#print axioms Navier.Routes.R7.squaredFrequency_neg
#print axioms Navier.Routes.R7.viscosityMultiplier_neg_frequency
#print axioms Navier.Routes.R7.viscosityMultiplier_conjugate
#print axioms Navier.Routes.R7.viscousLinearRHS_neg_output
#print axioms Navier.Routes.R7.finiteProjectedNonlinearRHS_neg_output
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_neg_output
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_preserves_reality
#print axioms Navier.Routes.R7.generatedSupport_finiteAmplitudeRHS_preserves_reality
#print axioms Navier.Routes.R7.nsmul_mem_of_pairwiseAddClosed
#print axioms Navier.Routes.R7.nsmul_injective_of_ne_zero
#print axioms Navier.Routes.R7.mem_eq_zero_of_finite_pairwiseAddClosed
#print axioms Navier.Routes.R7.eq_singleton_zero_of_finite_pairwiseAddClosed
#print axioms Navier.Routes.R7.generatedSupportStep_eq_self_iff_pairwiseAddClosed
#print axioms Navier.Routes.R7.nontrivial_centrallySymmetric_generatedSupportStep_ne_self
#print axioms Navier.Routes.R7.scaledSymWitnessModeWave_posK_ne_zero
#print axioms Navier.Routes.R7.generatedSupport_ssubset_succ
#print axioms Navier.Routes.R7.generatedSupport_card_lt_succ
#print axioms Navier.Routes.R7.generatedSupport_strictMono
#print axioms Navier.Routes.R7.generatedSupport_card_strictMono
#print axioms Navier.Routes.R7.exists_new_frequency_generatedSupport_succ
#print axioms Navier.Routes.R7.generation_le_generatedSupport_card
#print axioms Navier.Routes.R7.generatedSupport_card_unbounded
#print axioms Navier.Routes.R7.generatedSupport_not_eventually_constant
