import Navier.Analysis.CriticalControlDecomposition
import Navier.Analysis.CriticalMildRestartFixedPoint
import Navier.Analysis.CriticalMildBoundedContinuation
import Navier.Analysis.LeiLinCoerciveTerminal
import Navier.Analysis.LerayWeak
import Navier.Analysis.HeatSemigroupSmoothing
import Navier.Analysis.BKMLogBootstrap
import Navier.Analysis.ViscosityEndpoints
import Navier.Breakdown.MaximalNonextension
import Navier.Breakdown.CompactPathBreakdown
import Navier.Breakdown.ConstructedBreakdown
import Navier.Analysis.ForcedEnergyBalance

/-! Selected consumer-facing conditions and the constructed alternative-C
endpoint; not a project-wide census.
Checks inspect existing imported objects. Rebuild changed providers before
using axiom output as current-source evidence. Audit commands inspect proofs;
they do not manufacture them. -/

#check Navier.Construction.R3CompactCandidate.selected_compact_candidate
#print axioms Navier.Construction.R3CompactCandidate.selected_compact_candidate

#check Navier.Construction.ComparatorBridge.compact_candidate_excludes_global_solution
#print axioms Navier.Construction.ComparatorBridge.compact_candidate_excludes_global_solution

#check Navier.Breakdown.NativeConstructionEndpoint.wholeSpaceBreakdown_of_compactCandidate
#print axioms Navier.Breakdown.NativeConstructionEndpoint.wholeSpaceBreakdown_of_compactCandidate

#check Navier.Breakdown.ConstructedBreakdown.wholeSpaceBreakdown
#print axioms Navier.Breakdown.ConstructedBreakdown.wholeSpaceBreakdown
#check Navier.Analysis.ConstructedForceExtension.constructedWholeSpaceBreakdownWithGloballySmoothForce
#print axioms Navier.Analysis.ConstructedForceExtension.constructedWholeSpaceBreakdownWithGloballySmoothForce
#check Navier.Breakdown.ConstructedBreakdown.wholeSpaceBreakdown_with_successivePartials
#print axioms Navier.Breakdown.ConstructedBreakdown.wholeSpaceBreakdown_with_successivePartials

#check Navier.Analysis.CriticalControlDecomposition.wholeSpaceGlobalRegularity_of_local_continuation_apriori
#print axioms Navier.Analysis.CriticalControlDecomposition.wholeSpaceGlobalRegularity_of_local_continuation_apriori

#check Navier.Analysis.CriticalMildRestartFixedPoint.existsUnique_criticalMildTerminalRestart_fixedPoint
#print axioms Navier.Analysis.CriticalMildRestartFixedPoint.existsUnique_criticalMildTerminalRestart_fixedPoint

#check Navier.Analysis.CriticalMildBoundedContinuation.bounded_global_mild_of_terminalNormBound
#print axioms Navier.Analysis.CriticalMildBoundedContinuation.bounded_global_mild_of_terminalNormBound

#check Navier.Analysis.LeiLinCoerciveTerminal.criticalMildTerminalNormBound_of_mixed
#print axioms Navier.Analysis.LeiLinCoerciveTerminal.criticalMildTerminalNormBound_of_mixed

#check Navier.Analysis.LeiLinCoerciveTerminal.terminal_X1_le_of_trailingMass_and_X2Mass
#print axioms Navier.Analysis.LeiLinCoerciveTerminal.terminal_X1_le_of_trailingMass_and_X2Mass

#check Navier.Analysis.LerayWeak.exists_galerkinLimit_energy_le
#print axioms Navier.Analysis.LerayWeak.exists_galerkinLimit_energy_le

#check Navier.Analysis.LerayWeak.exists_lerayLimitData_of_weakClauses
#print axioms Navier.Analysis.LerayWeak.exists_lerayLimitData_of_weakClauses

#check Navier.Analysis.HeatSemigroupSmoothing.heatKernel_convolution_smoothing_le
#print axioms Navier.Analysis.HeatSemigroupSmoothing.heatKernel_convolution_smoothing_le

#check Navier.Analysis.BealeKatoMajda.exists_fderivSupBound_of_sobolevH3
#print axioms Navier.Analysis.BealeKatoMajda.exists_fderivSupBound_of_sobolevH3

#check Navier.Analysis.ViscosityEndpoints.wholeSpaceBreakdown_iff_atViscosityOne
#print axioms Navier.Analysis.ViscosityEndpoints.wholeSpaceBreakdown_iff_atViscosityOne

#check Navier.Breakdown.noWholeSpaceGlobal_of_pointEvaluationBreakdown
#print axioms Navier.Breakdown.noWholeSpaceGlobal_of_pointEvaluationBreakdown

#check Navier.Breakdown.wholeSpaceBreakdown_of_compactSmooth_negativePowerProfile
#print axioms Navier.Breakdown.wholeSpaceBreakdown_of_compactSmooth_negativePowerProfile

#check Navier.Analysis.ForcedEnergyBalance.forced_pointwise_energy_balance_of_partialSolution
#print axioms Navier.Analysis.ForcedEnergyBalance.forced_pointwise_energy_balance_of_partialSolution
