import Navier.Analysis.CKNIntegralScaling
import Navier.Analysis.EnergyNormBridge
import Navier.Analysis.EnergyOfficialClause
import Navier.Analysis.FrequencyHeatLeray
import Navier.Analysis.ComplexLerayProjection
import Navier.Analysis.ComplexLerayNorm
import Navier.Analysis.ComplexFrequencyHeatLeray
import Navier.Analysis.EnergyConvectionCancellation
import Navier.Analysis.EnergyConvectionIntegral
import Navier.Analysis.EnergyTimeDerivative
import Navier.Analysis.EnergyViscousDissipation
import Navier.Analysis.EnergyViscousIntegral
import Navier.Analysis.EnergyPointwiseBalance
import Navier.Analysis.EnergyInstantaneousIntegralBalance
import Navier.Analysis.EnergyDerivativeUnderIntegral
import Navier.Routes.R7.GeneratedSupport
import Navier.Routes.R7.FiniteConvolution
import Navier.Routes.R7.FiniteAmplitudeDynamics
import Navier.Routes.R7.FiniteReality
import Navier.Routes.R7.FiniteSupportClosureObstruction
import Navier.Routes.R7.GeneratedSupportStrictGrowth

/-!
# Raw axiom audit for the resumed full-map attack

These commands audit every public theorem introduced by the resumed local,
energy, CKN-scaling, and generated-frequency leaves.  They certify only the
named support theorems.  In particular they do not construct an inhabitant of
an official Clay endpoint.
-/

#print axioms Navier.Analysis.CKNCylinder.det_parabolicPointEquiv
#print axioms Navier.Analysis.CKNCylinder.map_parabolicPointEquiv_spaceTimeVolume
#print axioms Navier.Analysis.CKNCylinder.setIntegral_comp_parabolicPointMap
#print axioms Navier.Analysis.CKNCylinder.setIntegral_comp_parabolicPointMap_backwardEuclideanCylinder
#print axioms Navier.Analysis.CKNCylinder.cknDensityIntegral_parabolicScaled
#print axioms Navier.Analysis.CKNCylinder.normalizedCKNFunctional_parabolicScaled

#print axioms Navier.Analysis.EnergyNormBridge.continuous_officialEuclideanNorm
#print axioms Navier.Analysis.EnergyNormBridge.norm_sq_le_officialEuclideanNorm_sq
#print axioms Navier.Analysis.EnergyNormBridge.officialEuclideanNorm_sq_le_three_mul_norm_sq
#print axioms Navier.Analysis.EnergyNormBridge.integrable_norm_sq_iff_officialEuclideanNorm_sq
#print axioms Navier.Analysis.EnergyNormBridge.kineticEnergy_le_officialKineticEnergy
#print axioms Navier.Analysis.EnergyNormBridge.officialKineticEnergy_le_three_mul_kineticEnergy
#print axioms Navier.Analysis.EnergyNormBridge.uniformlyBoundedEnergy_iff_official

#print axioms Navier.Analysis.EnergyOfficialClause.officialEuclideanNorm_sq_eq_sum_sq
#print axioms Navier.Analysis.EnergyOfficialClause.officialKineticEnergy_eq_coordinateKineticEnergy
#print axioms Navier.Analysis.EnergyOfficialClause.officialWholeSpaceEnergyClause_iff_coordinate
#print axioms Navier.Analysis.EnergyOfficialClause.currentWholeSpaceEnergyClause_iff_official
#print axioms Navier.Analysis.EnergyOfficialClause.IsClassicalSolution.velocity_slice_continuous
#print axioms Navier.Analysis.EnergyOfficialClause.IsClassicalSolution.velocity_slice_aestronglyMeasurable
#print axioms Navier.Analysis.EnergyOfficialClause.IsClassicalSolution.officialWholeSpaceEnergyClause
#print axioms Navier.Analysis.EnergyOfficialClause.IsClassicalSolution.coordinateWholeSpaceEnergyClause

#print axioms Navier.Analysis.FrequencyHeatLeray.frequencyHeatLeray_apply
#print axioms Navier.Analysis.FrequencyHeatLeray.frequencyHeatLeray_zero_time
#print axioms Navier.Analysis.FrequencyHeatLeray.frequencyHeatLeray_zero_frequency
#print axioms Navier.Analysis.FrequencyHeatLeray.frequencyHeatLeray_transverse
#print axioms Navier.Analysis.FrequencyHeatLeray.heatDecay_nonneg
#print axioms Navier.Analysis.FrequencyHeatLeray.heatDecay_le_one
#print axioms Navier.Analysis.FrequencyHeatLeray.frequencyHeatLeray_norm_le
#print axioms Navier.Analysis.FrequencyHeatLeray.frequencyHeatLeray_semigroup

#print axioms Navier.Analysis.ComplexLerayProjection.complexOfParts_apply
#print axioms Navier.Analysis.ComplexLerayProjection.complexOfParts_re
#print axioms Navier.Analysis.ComplexLerayProjection.complexOfParts_im
#print axioms Navier.Analysis.ComplexLerayProjection.complexOfParts_real_imaginary
#print axioms Navier.Analysis.ComplexLerayProjection.realPart_add
#print axioms Navier.Analysis.ComplexLerayProjection.imaginaryPart_add
#print axioms Navier.Analysis.ComplexLerayProjection.realPart_smul
#print axioms Navier.Analysis.ComplexLerayProjection.imaginaryPart_smul
#print axioms Navier.Analysis.ComplexLerayProjection.realPart_complexConjugate
#print axioms Navier.Analysis.ComplexLerayProjection.imaginaryPart_complexConjugate
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_add
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_sub
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_smul
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_neg
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_zero_vector
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_transverse
#print axioms Navier.Analysis.ComplexLerayProjection.normalizedLeraySymbol_idempotent
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_apply
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_re
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_im
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_ofReal
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_zero_frequency
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_conjugate
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_idempotent
#print axioms Navier.Analysis.ComplexLerayProjection.complexLeray_transverse

#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanPoint_apply
#print axioms Navier.Analysis.ComplexLerayNorm.complexFrequency_apply
#print axioms Navier.Analysis.ComplexLerayNorm.complexFrequency_zero
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanLeray_mem
#print axioms Navier.Analysis.ComplexLerayNorm.inner_complexEuclideanLeray
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanLeray_norm_le
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanLeray_idempotent
#print axioms Navier.Analysis.ComplexLerayNorm.inner_complexFrequency
#print axioms Navier.Analysis.ComplexLerayNorm.complexFrequency_norm_sq
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanLeray_formula
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanLeray_zero_frequency
#print axioms Navier.Analysis.ComplexLerayNorm.complexBilinearDot_parts
#print axioms Navier.Analysis.ComplexLerayNorm.complex_division_of_parts
#print axioms Navier.Analysis.ComplexLerayNorm.complexLeray_formula
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanPoint_complexLeray
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanNorm_complexLeray_le
#print axioms Navier.Analysis.ComplexLerayNorm.complexLeray_hermitian_transverse
#print axioms Navier.Analysis.ComplexLerayNorm.complexLeray_bilinear_transverse_smoke
#print axioms Navier.Analysis.ComplexLerayNorm.complexEuclideanPoint_injective
#print axioms Navier.Analysis.ComplexLerayNorm.complexLeray_idempotent_smoke

#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_apply
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_apply_coordinate
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_coordinate_formula
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexEuclideanPoint_smul
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_zero_time
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_zero_frequency
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexHeatDecay_nonneg
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexHeatDecay_le_one
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexEuclideanPoint_complexFrequencyHeatLeray
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_hermitian_transverse
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_bilinear_transverse
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexEuclideanNorm_complexFrequencyHeatLeray_le
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexHeatDecay_add
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_semigroup
#print axioms Navier.Analysis.ComplexFrequencyHeatLeray.complexFrequencyHeatLeray_conjugate

#print axioms Navier.differentiableAt_kineticEnergyDensity
#print axioms Navier.fderiv_kineticEnergyDensity
#print axioms Navier.staticGradient_kineticEnergyDensity
#print axioms Navier.convection_work_eq_staticDivergence
#print axioms Navier.convection_work_eq_staticDivergence_of_incompressible

#print axioms Navier.Analysis.EnergyConvectionIntegral.convection_work_integrand_eq_staticDivergence
#print axioms Navier.Analysis.EnergyConvectionIntegral.integral_convection_work_eq_zero

#print axioms Navier.differentiableWithinAt_timeSlice_of_smoothVelocity
#print axioms Navier.differentiableWithinAt_kineticEnergyDensity_time
#print axioms Navier.fderivWithin_kineticEnergyDensity_time
#print axioms Navier.kineticEnergyDensity_timeDerivative
#print axioms Navier.kineticEnergyDensity_timeDerivative_of_smoothVelocity
#print axioms Navier.kineticEnergyDensity_timeDerivative_eq_work
#print axioms Navier.kineticEnergyDensity_timeDerivative_eq_work_of_classicalSolution

#print axioms Navier.Analysis.EnergyViscousDissipation.derivativeEnergyDensity_nonneg
#print axioms Navier.Analysis.EnergyViscousDissipation.differentiableAt_viscousEnergyFlux
#print axioms Navier.Analysis.EnergyViscousDissipation.fderiv_viscousEnergyFlux_component
#print axioms Navier.Analysis.EnergyViscousDissipation.staticDivergence_viscousEnergyFlux
#print axioms Navier.Analysis.EnergyViscousDissipation.laplacian_work_eq_secondDerivative_sum
#print axioms Navier.Analysis.EnergyViscousDissipation.laplacian_work_eq_divergence_sub_derivativeEnergy
#print axioms Navier.Analysis.EnergyViscousDissipation.laplacian_work_add_derivativeEnergy_eq_divergence

#print axioms Navier.Analysis.EnergyViscousIntegral.differentiable_viscousEnergyFlux
#print axioms Navier.Analysis.EnergyViscousIntegral.integrable_staticDivergence_of_coordinatewise
#print axioms Navier.Analysis.EnergyViscousIntegral.integrable_laplacian_work_of_viscous_flux
#print axioms Navier.Analysis.EnergyViscousIntegral.integral_laplacian_work_eq_neg_derivativeEnergy

#print axioms Navier.Analysis.EnergyPointwiseBalance.contDiff_spatialSlice_of_smoothVelocity
#print axioms Navier.Analysis.EnergyPointwiseBalance.contDiff_spatialSlice_of_smoothPressure
#print axioms Navier.Analysis.EnergyPointwiseBalance.differentiable_coordinateDerivativeField_of_contDiff
#print axioms Navier.Analysis.EnergyPointwiseBalance.zeroForce_pointwise_energy_balance
#print axioms Navier.Analysis.EnergyPointwiseBalance.zeroForce_pointwise_energy_balance_of_classicalSolution

#print axioms Navier.Analysis.EnergyInstantaneousIntegralBalance.kineticEnergyDensity_timeDerivative_eq_zeroForce_work
#print axioms Navier.Analysis.EnergyInstantaneousIntegralBalance.integrable_pressure_work_of_flux
#print axioms Navier.Analysis.EnergyInstantaneousIntegralBalance.integrable_convection_work_of_flux
#print axioms Navier.Analysis.EnergyInstantaneousIntegralBalance.integrable_kineticEnergyDensity_timeDerivative_of_zeroForce
#print axioms Navier.Analysis.EnergyInstantaneousIntegralBalance.integral_kineticEnergyDensity_timeDerivative_eq_neg_viscousDissipation

#print axioms Navier.Analysis.EnergyDerivativeUnderIntegral.fderivWithin_integral_kineticEnergyDensity_eq_integral_of_dominated

#print axioms Navier.Routes.R7.subset_generatedSupportStep
#print axioms Navier.Routes.R7.add_mem_generatedSupportStep
#print axioms Navier.Routes.R7.generatedSupport_subset_succ
#print axioms Navier.Routes.R7.generatedSupport_mono
#print axioms Navier.Routes.R7.add_mem_generatedSupport_succ
#print axioms Navier.Routes.R7.scaledSymWitnessModeWave_mem_generatedSupport_zero
#print axioms Navier.Routes.R7.scaledSymWitnessModeWave_mem_generatedSupport
#print axioms Navier.Routes.R7.leakOutputWave_not_mem_generatedSupport_zero
#print axioms Navier.Routes.R7.leakOutputWave_eq_negK_add_posL
#print axioms Navier.Routes.R7.leakOutputWave_mem_generatedSupport_one
#print axioms Navier.Routes.R7.leakOutputWave_enters_at_generation_one
#print axioms Navier.Routes.R7.sixModeInitialSupport_centrallySymmetric
#print axioms Navier.Routes.R7.pairwiseMinkowskiSum_centrallySymmetric
#print axioms Navier.Routes.R7.generatedSupportStep_centrallySymmetric
#print axioms Navier.Routes.R7.generatedSupport_centrallySymmetric

#print axioms Navier.Routes.R7.complexBilinearDot_add_left
#print axioms Navier.Routes.R7.complexBilinearDot_add_right
#print axioms Navier.Routes.R7.complexBilinearDot_smul_left
#print axioms Navier.Routes.R7.complexBilinearDot_smul_right
#print axioms Navier.Routes.R7.complexWaveDot_add
#print axioms Navier.Routes.R7.complexWaveDot_smul
#print axioms Navier.Routes.R7.orderedConvectionCoefficient_add_advecting
#print axioms Navier.Routes.R7.orderedConvectionCoefficient_add_advected
#print axioms Navier.Routes.R7.orderedConvectionCoefficient_smul_advecting
#print axioms Navier.Routes.R7.orderedConvectionCoefficient_smul_advected
#print axioms Navier.Routes.R7.add_mem_pairwiseMinkowskiSum
#print axioms Navier.Routes.R7.finiteConvectionCoefficient_eq_zero_of_not_mem_pairwiseMinkowskiSum
#print axioms Navier.Routes.R7.projectedFiniteConvectionCoefficient_eq_zero_of_not_mem_pairwiseMinkowskiSum
#print axioms Navier.Routes.R7.projectedFiniteConvectionCoefficient_divergence
#print axioms Navier.Routes.R7.projectedFiniteConvectionCoefficient_already_projected

#print axioms Navier.Routes.R7.complexWaveDot_neg_wave
#print axioms Navier.Routes.R7.complexWaveDot_neg_amplitude
#print axioms Navier.Routes.R7.complexWaveDot_sub
#print axioms Navier.Routes.R7.squaredFrequency_zero
#print axioms Navier.Routes.R7.viscosityMultiplier_zero_frequency
#print axioms Navier.Routes.R7.viscousLinearRHS_zero_frequency
#print axioms Navier.Routes.R7.viscousLinearRHS_eq_zero_of_not_mem
#print axioms Navier.Routes.R7.finiteProjectedNonlinearRHS_eq_zero_of_not_mem_pairwiseMinkowskiSum
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_eq_zero_of_not_mem_generatedSupportStep
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_supportedOn_generatedSupportStep
#print axioms Navier.Routes.R7.finiteConvectionCoefficient_zero_output
#print axioms Navier.Routes.R7.projectedFiniteConvectionCoefficient_zero_output
#print axioms Navier.Routes.R7.finiteProjectedNonlinearRHS_zero_output
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_zero_output
#print axioms Navier.Routes.R7.viscousLinearRHS_divergence
#print axioms Navier.Routes.R7.finiteProjectedNonlinearRHS_divergence
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_divergence
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_modewiseDivergenceFree

#print axioms Navier.Routes.R7.coordinateConjugate_apply
#print axioms Navier.Routes.R7.coordinateConjugate_zero
#print axioms Navier.Routes.R7.coordinateConjugate_add
#print axioms Navier.Routes.R7.coordinateConjugate_neg
#print axioms Navier.Routes.R7.coordinateConjugate_smul
#print axioms Navier.Routes.R7.coordinateConjugate_involutive
#print axioms Navier.Routes.R7.coordinateConjugate_eq_complexConjugate
#print axioms Navier.Routes.R7.complexWaveDot_coordinateConjugate
#print axioms Navier.Routes.R7.normalizedLeraySymbol_neg_frequency
#print axioms Navier.Routes.R7.complexLeray_neg_frequency
#print axioms Navier.Routes.R7.complexLeray_neg_coordinateConjugate
#print axioms Navier.Routes.R7.orderedConvectionCoefficient_neg_coordinateConjugate
#print axioms Navier.Routes.R7.mem_support_neg_iff
#print axioms Navier.Routes.R7.pairSumsToOutput_neg_iff
#print axioms Navier.Routes.R7.coordinateConjugate_sum
#print axioms Navier.Routes.R7.finiteConvectionCoefficient_neg_output
#print axioms Navier.Routes.R7.projectedFiniteConvectionCoefficient_neg_output
#print axioms Navier.Routes.R7.squaredFrequency_neg
#print axioms Navier.Routes.R7.viscosityMultiplier_neg_frequency
#print axioms Navier.Routes.R7.viscosityMultiplier_conjugate
#print axioms Navier.Routes.R7.viscousLinearRHS_neg_output
#print axioms Navier.Routes.R7.finiteProjectedNonlinearRHS_neg_output
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_neg_output
#print axioms Navier.Routes.R7.finiteAmplitudeRHS_preserves_reality
#print axioms Navier.Routes.R7.generatedSupport_finiteAmplitudeRHS_preserves_reality

#print axioms Navier.Routes.R7.nsmul_mem_of_pairwiseAddClosed
#print axioms Navier.Routes.R7.nsmul_injective_of_ne_zero
#print axioms Navier.Routes.R7.mem_eq_zero_of_finite_pairwiseAddClosed
#print axioms Navier.Routes.R7.eq_singleton_zero_of_finite_pairwiseAddClosed
#print axioms Navier.Routes.R7.generatedSupportStep_eq_self_iff_pairwiseAddClosed
#print axioms Navier.Routes.R7.nontrivial_centrallySymmetric_generatedSupportStep_ne_self

#print axioms Navier.Routes.R7.scaledSymWitnessModeWave_posK_ne_zero
#print axioms Navier.Routes.R7.generatedSupport_ssubset_succ
#print axioms Navier.Routes.R7.generatedSupport_card_lt_succ
#print axioms Navier.Routes.R7.generatedSupport_strictMono
#print axioms Navier.Routes.R7.generatedSupport_card_strictMono
#print axioms Navier.Routes.R7.exists_new_frequency_generatedSupport_succ
#print axioms Navier.Routes.R7.generation_le_generatedSupport_card
#print axioms Navier.Routes.R7.generatedSupport_card_unbounded
#print axioms Navier.Routes.R7.generatedSupport_not_eventually_constant
